<?php

$imageName = array(
		array("civipack.png","Civilian Vehicles - in a small city")
		,array("emergency.png","Emergency vehicles in destroyed city")
		,array("furyroad.png","A scene recreation of Mad Max Fury Road")
		,array("mario.png","Mario Kart... What else needs to be said...")
		,array("metroid.png","Samus Aran lands on planet Earth after receiving distress call...")
		,array("race.png","A race track with race cars at the ready line")
		,array("wild.png","A small wild west town")
		,array("emp01.jpg","Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge")
		,array("emp02.png","Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge")
		,array("emp03.png","Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge")
		,array("russiabase.png","Failed mod that attempted to give each country its own set of unique buildings")
		,array("alliedmech.png","Very pretty screenshot of allied stuff")
		,array("ren2006.png","Two units converted from C&C Renegade")
		,array("gdicannon2.PNG","A cannon I made years ago for C&C TS")
		,array("TSPOWNS2006.PNG","A TS/FS screenshot of two new buildings for Nod")
		,array("holdline.JPG","Screenshot of T-Day a failed mod called Tanyas revenge, this screenshot recreats d-day")
		,array("civiwar2.jpg","A Failed civil war mod")
		,array("civiwar02.PNG","A Failed civil war mod")
		,array("civiwar03.PNG","A Failed civil war mod")
		,array("id1.JPG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("id2.JPG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("ronten.JPG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("ronten3.JPG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("zorgon.gif","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("rollermech2.PNG","A high-ish polly render of a unit from Internal Destruction a Total Conversion for YR from 2005")
		,array("attackgonebad.JPG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("hehe.JPG","Screenshot of my first mod idea that was to become Internal Destruction from 2004")
		,array("wolfID2004.JPG","A early 3d render, inspired by TS wolverine from 2004")
		,array("mad2003.png","A collection of my earliest graphics work from 2003")
		,array("oneside.JPG","A collection of my earliest graphics work from 2003, all voxels made by hand in vxl edit")
		,array("otherside.JPG","A collection of my earliest graphics work from 2003, all voxels made by hand in vxl edit")
		,array("swat.png","Full S.W.A.T. deployment for terrorist at einstein's laboratory")
		,array("train01.png","An old-ish time train passes through a facotry and suburban part of a city")
		,array("train02.png","A factory part of town with convenient train docking")
		,array("train03.png","A downtown Train Station with a few trains waiting to depart")
		,array("sixhummers.png","Come on down to MadHQ's used car lot! All hummers 20% off!")
		,array("jurassic.png","NA-NUH-NA-NA-NAH! Welcome to Jurassic Park!")
		,array("arace.png","The fast and the furious Red Alert 2 style")
		,array("rsfreedoom.png","Two Buildings I did for Robot Storm")
		,array("nod.PNG","A Failed TS remake for Ra2/Yr")
		,array("render.PNG","3d renders of buildings found on this site")
		,array("renjunk.PNG","C&C Renegade buildings rendered for Ra2/YR")
		,array("xmassmodfake.png","A Failed X-mas mod")
		,array("monsters.gif","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("genfction.png","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("barx.gif","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("lzrgn.gif","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("plnt.gif","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("temp.PNG","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("uscnyd.gif","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("untitled_500.gif","A re-creation of Red Alert 3's Japan Hero Unit")
		,array("modernwarz_560.png","A collection of concept work by me to see if I wanted to make a mod with it")
		,array("gaion_212.gif","A un-used design for a allied ion cannon")
		,array("sov_114.png","3 un-used soviet building designs")
		,array("nanuke_164.gif","An un-used soviet nuke silo building design")
		,array("yanuke_820.gif","An un-used yuri nuke silo building design")
		,array("WIP1.png","An Conkers bad fur day concept")
		,array("banner.gif","A banner to my old Ra2 Madness site")
		,array("build.PNG","Some concept I did for a mod I was trying to create, called 'Mechanical Eradication' (2010)")
		,array("civibuildings.PNG","A bunch of civi buildings")
		,array("DOW.PNG","An attempt to make a Dawn of war mod (failed)")
		,array("fakeasiawip.png","A first pass at an empire of the rising sun faction")
		,array("FLNUKE3.gif","A building I did for Robot Storm")
		,array("floatioingisland4.PNG","A small floating island style map")
		,array("FLTECHANMTST.gif","A building I did for Robot Storm")
		,array("indexbanner.gif","A banner for my very first mod Internal Destruction's web site")
		,array("JUGGWIP.gif","A unit for a lego mod I was once working on (failed)")
		,array("jugrender.PNG","A unit for a lego mod I was once working on (failed)")
		,array("LEGOTERRAIN.PNG","Terrain for a lego mod I was once working on (failed)")
		,array("LEGOTERRAIN2.PNG","Terrain for a lego mod I was once working on (failed)")
		,array("lol2.PNG","Space terrain made for fun.")
		,array("Middleearth.PNG","A collection of concept work by me to see if I wanted to make a mod with it")
		,array("oie_ReKdY0ub4B4z.gif","A bunch of spinning logos for a mod called Robot Storm")
		,array("preview.PNG","A collection of concept work by me to see if I wanted to make a mod with it")
		,array("RA_ALLIES.PNG","A collection of concept work by me to see if I wanted to make a mod with it")
		,array("ra2madness2008_01.PNG","A screenshot of RA2 Madness")
		,array("ra2madness2008_03.PNG","A screenshot of RA2 Madness")
		,array("TERAINSTUFF.PNG","Renders of terrain")
		,array("wh40k.PNG","Renders of terrain for a DOW theme")
		,array("yrbuild.PNG","A few unfinished Ra2 buildings")
		,array("weirdbarx.PNG","A Joke building I made for my mod Ra2 madness")
		,array("ra2gen.PNG","USA and GLA buildings rendered for Ra2 (failed)")
		,array("screen01.PNG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("screen02.PNG","Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005")
		,array("tanyapromo.JPG","Screenshot of T-Day a failed mod called Tanyas revenge")
		,array("tanyapromo1.gif","Screenshot of T-Day a failed mod called Tanyas revenge")
		,array("tanyapromo2.gif","Screenshot of T-Day a failed mod called Tanyas revenge")
		,array("TSMECHASST.PNG","Screenshot of some kind of odd TS-mech mod")
		);

?>