<?php

echo '<table class="newsblockheader" align="center">'
		. '<tr>'
			. '<td class="newsheader">'
				. 'Ra2 Madness: Re-Release Date: June 2015'
			. '</td>'
		. '</tr>'
	. '</table>'
	. '<table class="newsblockbody" align="center">'
		. '<tr>'
			. '<td class="newsbody">'
				. 'Ra2 Madness is a crazy mod, developed by me years ago. Though this mod was never finished, it is still kind of fun.<br>'
				. '<br>Caution this mod is very unbalanced, and could be very unstable.<br>'
				. '<br>Required to play: factory Red Alert 2: Yuri\'s Revenge.<br>'
				. 'To install mod, unpack 7zip file and add contents to ra2/yr directory.<br>'
				. '<br>Allies have two factions<br>'
				. '<table style="width:10%;" align="center"><tr><td>Tech</td><td>Robotics</td></tr><tr><td>'
				. '<a href="madness/madnessALIpower.png" target="_blank"><img class="mapimg" src="madness/mini/madnessALIpower.png"></a>'
				. '</td><td>'
				. '<a href="madness/madnessALIrobotics.png" target="_blank"><img class="mapimg" src="madness/mini/madnessALIrobotics.png"></a>'
				. '</td></tr></table>'
				. '<br>Soviets have two factions<br>'
				. '<table style="width:10%;" align="center"><tr><td>Terrorist</td><td>Power</td></tr><tr><td>'
				. '<a href="madness/madnessSOVterrorist.png" target="_blank"><img class="mapimg" src="madness/mini/madnessSOVterrorist.png"></a>'
				. '</td><td>'
				. '<a href="madness/madnessSOVpower.png" target="_blank"><img class="mapimg" src="madness/mini/madnessSOVpower.png"></a>'
				. '</td></tr></table>'
				. '<br>Yuri has two factions<br>'
				. '<table style="width:10%;" align="center"><tr><td>Mind Power</td><td>Brute Power</td></tr><tr><td>'
				. '<a href="madness/madnessYRmind.png" target="_blank"><img class="mapimg" src="madness/mini/madnessYRmind.png"></a>'
				. '</td><td>'
				. '<a href="madness/madnessYRbrute.png" target="_blank"><img class="mapimg" src="madness/mini/madnessYRbrute.png"></a>'
				. '</td></tr></table>'
				. '<br><br><a href="madness/RA2MadnessAlpha.7z" style="color:red;font-size:30px;" download>'
				. 'Click Here To Download'
				. '</a>'
			. '</td>'
		. '</tr>'
	. '</table>';

?>