<?php

$fileName="grave_counter.txt";

$file = fopen($fileName, "r");
$value=fread($file,filesize($fileName));
fclose($file);

++$value;

$file2 = fopen($fileName, "w");
fwrite($file2, $value);
fclose($file2);

$news=array(
	"Max McGrath","Summer 2015","Welcome to my graveyard.<br>Do not expect new content, I took a web scripting class last semester and wanted some thing to practice with."
		."<br>If you encounter a problems with the new site you can try to email me at MadHQ04@gmail.com."
	,"Max McGrath","October 2016","Happy Halloween!!!<br>"
		. "I have released 4 spooky themed maps for your enjoyment!<br>"
		. "<img src='maps/mini/witchmap.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/spidermap.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/devilmap.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/grimmap.png' style='width:100px;height:100px;'>&nbsp;"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","September 2016","A whole new download section!<br>"
		. "For years I have been asked how did I make Ra2/YR buildings, or can I release the 3d models and textures. The reasons I have never wanted<br>"
		. "to, is because my 3d skills are not spectacular, and it would most likely require someone to have the same programs I use, so it just<br>"
		. "seemed kind of point-less. But seeing as I do not care to much any more, and this site is pretty much just a collection of stuff any ways,<br>"
		. "I might as well put them up for download. I have released one building of each faction, so maybe some one can find them helpfull.<br>"
		. "And if this is some thing people like, I can release more, if I still have them...<br>"
		. "So take note*** these 3d models will need 3ds max 2013 or newer to open.<br><br>"
		. "<img src='3dmodels/image/GAWEATHER.png' style='max-width:325px;'>&nbsp;"
		. "<img src='3dmodels/image/NABARX.png' style='max-width:325px;'><br>"
		. "<img src='3dmodels/image/YAPUPET.png' style='max-width:325px;'>"
		. "<br>They are located in the 3d model area."
	,"Max McGrath","September 2016","Some more junk heading your way!<br>"
		. "<br>So, I just recently purchased a hard drive to USB adapter thing. This gave me the opportunity to hunt through my now dead desktop"
		. "<br>hard drive. On this drive I found lots of unfinished stuff that I figured I could put up on the site."
		. "<br><br>Starting off this larger then normal news post, is what I hope is the most current version of my Empire Of The Rising Sun mod."
		. "<br>Note** as with most of my stuff it is not complete, but should still be playable."
		. "<br>In the left side bar you should find a link to download the mod and a little info."
		. "<br><img src='empireMod/empire.png' style='max-width:400px;'>&nbsp;"
		. "<br><br>"
		. "<br>Along with the mod I have decided to release all assets from the mod in individual downloads."
		. "<br>The images below show some of resources, and of course not all are finished, but could be usable.<br>"
		. "<img src='shp/image/eacnyrd.png'>&nbsp;"
		. "<img src='shp/image/eabarx.png'>&nbsp;"
		. "<img src='shp/image/eatch.png'>&nbsp;"
		. "<br>"
		. "<img src='shp/image/yuriko.png'>&nbsp;"
		. "<img src='shp/image/ninja.png'>&nbsp;"
		. "<img src='shp/image/rctangl.png'>&nbsp;"
		. "<br>"
		. "<img src='shp/image/sidec04.png'>&nbsp;"
		. "<br><br>"
		. "<br>Up next is some terrain sets that I was working on. None were 100% finished but could be used"
		. "<br>if someone is clever enough. This news post only shows 2 of the 4 sets.<br>"
		. "<img src='shp/image/legotemp.PNG'>&nbsp;"
		. "<img src='shp/image/float.png' style='max-width:300px;'>&nbsp;"
		. "<br><br>"
		. "<br>Moveing right along, there are some more voxels added to the site."
		. "<br>This news post only shows some of the voxels, there are a few others not shown here.<br>"
		. "<img src='vxl/image/aqtnk.png'>&nbsp;"
		. "<img src='vxl/image/mammy.png'>&nbsp;"
		. "<img src='vxl/image/utnk.png'>&nbsp;"
		. "<br>"
		. "<img src='vxl/image/b2.png'>&nbsp;"
		. "<img src='vxl/image/humr.png'>&nbsp;"
		. "<img src='vxl/image/enagin.png'>&nbsp;"
		. "<br><br>"
		. "<br>Even more junk! Ha! So I have also added a bunch of unfinished buildings and units."
		. "<br>This news post only shows some of the shapes, there are others not shown here.<br>"
		. "<img src='shp/image/modern.png'>&nbsp;"
		. "<img src='shp/image/gawhtr.png'>&nbsp;"
		. "<img src='shp/image/GGREFNX.png'>&nbsp;"
		. "<img src='shp/image/naion.png'>&nbsp;"
		. "<br>"
		. "<img src='shp/image/nabarx.png'>&nbsp;"
		. "<img src='shp/image/bear.png'>&nbsp;"
		. "<img src='shp/image/naweap2.png'>&nbsp;"
		. "<img src='shp/image/ngcybcr.png'>&nbsp;"
		. "<br><br>"
		. "<br>And now finally, I have released three more maps. I am always happy to add more maps to my largely growing collection.<br>"
		. "<img src='maps/mini/junglebasin.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/valleydeath.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/credit.png' style='width:100px;height:100px;'>&nbsp;"
		. "<br><br>I also found and added some more images to the gallery.<br>By now you should be able to find this crap."
	,"Max McGrath","September 2016","A little blast from my past!<br>"
		. "While cleaning my apartment I found an old flash drive I used for back-up. So I investigated what was on it.<br>"
		. "Now, there was not too much, or really anything of value. However, I figure I can release whatever I want.<br>"
		. "<br>There was 5 maps (all of which I had to make a lazy attempt to finish).<br>"
		. "<img src='maps/mini/marland.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/dcolombia.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/skullis.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/soviet.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/circaljerk.png' style='width:100px;height:100px;'>&nbsp;<br>"
		. "<br>There was also 2 voxels that I thought I had lost (Two Renegade conversions).<br>"
		. "<br><table><tr><td>"
			. "<img src='vxl/image/renorca.png'>"
		. "</td><td>"
			. "<img src='vxl/image/renhummer.png'>"
		. "</td></tr><tr><td>"
			. "Renegade Orca"
		. "</td><td>"
			. "Renegade Humvee"
		. "</td></tr></table>"
		. "<br>There was also a few unfinished shp's, and there was a collection of map doodad things.<br>"
		. "<br><table><tr><td>"
			. "<img src='shp/image/orcinfy.png'>"
		. "</td><td>"
			. "<img src='shp/image/gdiinfy.png'>"
		. "</td><td>"
			. "<img src='shp/image/nodinfy.png'>"
		. "</td></tr><tr><td>"
			. "Orc Unit"
		. "</td><td>"
			. "GDI Infantry"
		. "</td><td>"
			. "Nod Infantry"	
		. "</td></tr></table>"
		. "<br><table><tr><td>"
			. "<img src='shp/image/oddpack01.png' style='max-width:400px;'>&nbsp;"
		. "</td><td>"
			. "<img src='shp/image/tscannon.png'>"
		. "</td></tr><tr><td>"
			. "Doodad Things"
		. "</td><td>"
			. "GDI Cannon"
		. "</td></tr></table>"

		. "<br><br>The flash drive also contains audio sets for two units I record for one of Allied General mods.<br>"
		. "The mod is long since gone and dead, so I might as well put them here for a laugh.<br>"
		. "I created a audio section in the left sidebar other section if you want to listen/laugh/download, the recording is not great.<br>"
		. "I have added 3 wav files of each set to this news post, there are more in the audio section.<br>"
		. "<table><tr><td>"
			. "<br><audio style='width: 75%;' controls><source src='other/sound/madhq11.wav' type='audio/wav'></audio><br>"
			. "<audio style='width: 75%;' controls><source src='other/sound/madhq3.wav' type='audio/wav'></audio><br>"
			. "<audio style='width: 75%;' controls><source src='other/sound/madhq8.wav' type='audio/wav'></audio>"
		. "</td><td>"
			. "<br><audio style='width: 75%;' controls><source src='other/sound/zomba2.wav' type='audio/wav'></audio><br>"
			. "<audio style='width: 75%;' controls><source src='other/sound/zomba4.wav' type='audio/wav'></audio><br>"
			. "<audio style='width: 75%;' controls><source src='other/sound/zomba5.wav' type='audio/wav'></audio>"
		. "</td></tr><tr><td>"
			. "MadHQ"
		. "</td><td>"
			. "Zomba"	
		. "</td></tr></table>"
		. "<br><br>I also found and added some more images to the gallery.<br>By now you should be able to find this crap."
	,"Max McGrath","September 2016","I have released 4 new maps.<br>"
		. "For fun, I have recorded speed builds of each map, click a minmap to watch (YouTube link opens in new window/tab).<br>"
		. "<a href='https://www.youtube.com/watch?v=IvTmfWsgkYw' target='_blank'><img src='maps/mini/company.png' style='width:100px;height:100px;'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=2EuuhOCioho' target='_blank'><img src='maps/mini/desometro.png' style='width:100px;height:100px;'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=g9hc0HLgKo4' target='_blank'><img src='maps/mini/theseam.png' style='width:100px;height:100px;'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=mrRe290TbVM' target='_blank'><img src='maps/mini/sextuplet.png' style='width:100px;height:100px;'>&nbsp;</a>"
		. "<br>They are on the 2nd page of map area."
	,"Max McGrath","August 2016","I have released 4 new maps. Probably not usable with other mods.<br>"
		. "Now these maps are a little odd... Every once in a wail I like to do some thing different.<br>"
		. "In this case, these maps spawn lots of neutral units that move across the map.<br>"
		. "<img src='maps/mini/roadrage.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/virginmoscow.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/toarc.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/autodown.png' style='width:100px;height:100px;'>&nbsp;"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","July 2016","I have released 6 new maps.<br>"
		. "<img src='maps/mini/nora.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/mirageshock.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/dahlac.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/kongsoya.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/abeloya.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/coburg.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","June 2016","I have released 6 new maps.<br>"
		. "<img src='maps/mini/bloodreef.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/aegean.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/rockysurf.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/santorini.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/agattu.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/tokashiki.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","June 2016","I have released 3 new maps.<br>I have also released 7 chopped maps for fun.<br>"
		. "<img src='maps/mini/carhift.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/terplant.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/portroy.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/midrap.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/fairgro.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "<img src='maps/mini/branboon.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/cenelev.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/normetro.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/nublar.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/downtown.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","March 2016","I have released 6 new maps.<br>"
		. "<img src='maps/mini/encroachment.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/pipe.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/bowtie.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/frostedreft.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/straight.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/dustava.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","March 2016","I have released 4 new maps.<br>"
		. "<img src='maps/mini/halo.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/pubcom.bmp' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/duscan.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/civvio.png' style='width:100px;height:100px;'>"
		. "<br>"
		. "They are on the 2nd page of map area."
	,"Max McGrath","February 2016","If you noticed or care, I have been making changes/fixes all over the place to this site.<br>"
		. "If you find any problems please let me know.<br><br>"
		. "Anyways, I Released three more Doodad Voxel Packs.<br><br>"
		. "<table align='center'><tr>"
		. "<td valign='top'>Civilian Work Vehicles VXL Pack #5</td>"
		. "<td valign='top'>Civilian Work Vehicles VXL Pack #7</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/civiwrkpack05.png' style='max-width:600px;'><br><br></td>"
		. "<td valign='top'><img src='vxl/image/civiwrkpack07.png' style='max-width:600px;'><br><br></td>"
		. "</tr><tr>"
		. "<td valign='top'>Civilian Work Vehicles VXL Pack #6</td>"
		. "<td valign='top'>I have also released 2 new maps</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/civiwrkpack06.png' style='max-width:400px;'></td>"
		. "<td valign='top'>"
		. "<img src='maps/mini/triplication.png' style='width:100px;height:100px;'>&nbsp;"
		. "<img src='maps/mini/pinch.png' style='width:100px;height:100px;'>"
		. "</td>"
		. "</tr></table><br>"
		. "Voxels are in other category in voxel section, and the maps are on the 2nd page of map area."
	,"Max McGrath","February 2016","Released three more Doodad Voxel Packs.<br>"
		. "<table align='center'><tr>"
		. "<td valign='top'>Civilian Ship Voxel Pack #2</td>"
		. "<td valign='top'>Civilian Ship Voxel Pack #3</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/shippack03.png' style='max-width:400px;'><br><br></td>"
		. "<td valign='top'><img src='vxl/image/shippack02.png' style='max-width:400px;'><br><br></td>"
		. "</tr><tr>"
		. "<td valign='top' colspan='2'>Civilian Ship Voxel Pack #4</td>"
		. "</tr><tr>"
		. "<td valign='top' colspan='2'><img src='vxl/image/shippack01.png' style='max-width:400px;'></td>"
		. "</tr></table><br>"
		. "Voxels are in other category in voxel section."
	,"Max McGrath","February 2016","Released two more Doodad Voxel Packs.<br><br>"
		. "<table align='center'><tr>"
		. "<td valign='top'>Holly-Weird VXL pack #4</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/hollyweird4.png' style='max-width:600px;'><br><br></td>"
		. "</tr><tr>"
		. "<td valign='top'>Civilian Van Pack #1</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/civivanpack.png' style='max-width:600px;'></td>"
		. "</tr></table><br>"
		. "Voxels are in other category in voxel section."
	,"Max McGrath","January 2016","I am really proud to showcase a new feature to this site. This feature is a .shp file viewer through HTML5 canvas.<br>"
		. "Though it is still very much W.I.P.,"
		. " So far it seems stable enough to build into this site.<br>Click the image bellow to view demo Ra2/Yr .shp files in viewer.<br><br>"
		. "Shape Canvas Painter<br>"
		. "<a href='shapedraw/drawshape.php?zipName=demo.zip&fileName=cons.shp' target='_blank' align='center' style='padding:0px;'>"
		. "<img src='image/canvas.png' style='max-width:120px;'>"
		. "<br>(Opens in new window/tab)</a>"
		. "<br><br>Now, there is sill much to do, such as:<br>animations, terrain (tiles,trees,cliff...), maybe another shp format compression., maybe look into some kind of pallet solution..."
		. "<br><br>This viewer is built into the SHP section of this site exactly like the Voxel viewer is.<br>"
		. "I have omitted a few sph files/downloads, as the viewer is not ready for them."
		. "<br>Other wise have fun and let me know if you experience any problems."
	,"Max McGrath","January 2016","Well seeing as this site is still growing and I am still hanging around, I felt as though I needed to add a few things.<br>"
		. "First: I have created a Permissions page that talks about permissions and legal crap.<br>"
		. "Second: I have created a F.A.Q. page as I get a lot of similar questions."
		. "<br><br>Moving on to something more pleasant...<br>This is the last of the assets I was working on for my modded missions.<br>"
		. "I thought it would be best to touch them up a little more before releasing them.<br><br>"
		. "<table align='center'><tr>"
		. "<td valign='top'>Civilian Work Vehicles Voxel Pack #4</td>"
		. "<td valign='top'>Civilian Ship Voxel Pack #1</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/civipack04.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='vxl/image/ship01.png' style='max-width:350px;'></td>"
		. "</tr></table><br>"
		. "Voxels are in other category in voxel section."
	,"Max McGrath","January 2016","Well I am giving up on a modded mission pack project I was working on. Ended up being too much work.<br>"
		."So I am just going to release things as they are. Not everything is complete what you see is pretty much it.<br>I am doing this because I want to spend more time "
		."playing with html5 stuff.<br><br>"
		. "<table align='center'><tr>"
		. "<td valign='top'>Sport Car Voxel Pack #1</td>"
		. "<td valign='top'>Sport Car Voxel Pack #2</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/sportpack01.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='vxl/image/sportpack02.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Civilian Pickup Truck Pack #1</td>"
		. "<td valign='top'>Civilian Pickup Truck Pack #2</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/truckpack01.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='vxl/image/truckpack02.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Boot Camp Doodad Pack #1</td>"
		. "<td valign='top'>Tables Doodad Pack #1</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='shp/image/bootcamppack.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='shp/image/tablepack1.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Vending Machine Doodad Pack #1</td>"
		. "<td valign='top'>Fair Ride Pack #1</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='shp/image/vendingpack.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='shp/image/fairpack1.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Wild West Doodad Pack #1</td>"
		. "<td valign='top'>Wild West Building Pack #1</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='shp/image/westbitspack.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='shp/image/westbuildpack01.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Wild West Building Pack #2</td>"
		. "<td valign='top'>Wild West Building Pack #3</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='shp/image/westbuildpack02.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='shp/image/westbuildpack03.png' style='max-width:350px;'></td>"
		. "</tr></table><br>"
		. "Sprites can be found in shp section, voxels are in other category in voxel section."
	,"Max McGrath","January 2016","Aw, SNAP! new assets even in this very new year!<br>Lets start the new year with some FUN!<br><br>"
		. "<table align='center'><tr>"
		. "<td valign='top' colspan='2'>Collection of simple Mario Kart sprites.</td>"
		. "</tr><tr>"
		. "<td valign='top' colspan='2' align='center'><img src='shp/image/mario.png' style='max-width:700px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>S.W.A.T Voxel Pack</td>"
		. "<td valign='top'>Civilian Hummer Voxel Pack</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/swat.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='vxl/image/hummerpack.png' style='max-width:350px;'></td>"
		. "</tr><tr>"
		. "<td valign='top'>Civilian Train Voxel Pack #1</td>"
		. "<td valign='top'>Civilian Train Voxel Pack #2</td>"
		. "</tr><tr>"
		. "<td valign='top'><img src='vxl/image/trainpack1.png' style='max-width:350px;'></td>"
		. "<td valign='top'><img src='vxl/image/trainpack2.png' style='max-width:350px;'></td>"
		. "</tr></table><br>"
		. "Mario sprites can be found in shp section, voxels are in other category in voxel section."
	,"Max McGrath","December 2015","Updates to the site all over the place!<br><br>"
		."***New site feature: I am really proud and excited for is this 3D point cloud render I created.<br>"
		."Note* This is still WORK-IN-PROGRESS so it can be a little buggy... <br>IE. hva locations/animations, turret/barrel have some issues... My 3d viewer still needs more work.<br>"
		."The 3 images below are demo links to official RA2/YR units.<br>"
		."<table style='width:100px;' align=center><tr><td>"
			."Allied Units<br>"
			."<a href='vxlrender/vxlrender.php?zipName=alliedunits.zip' target='_blank' align='center' style='padding:0px;'>"
			."<img src='image/render.png' style='max-width:120px;'></a>"
		."</td><td>"
			."Soviet Units<br>"
			."<a href='vxlrender/vxlrender.php?zipName=sovietunits.zip' target='_blank' align='center' style='padding:0px;'>"
			."<img src='image/render.png' style='max-width:120px;'></a>"
		."</td><td>"
			."Yuri Units<br>"
			."<a href='vxlrender/vxlrender.php?zipName=yuriunits.zip' target='_blank' align='center' style='padding:0px;'>"
			."<img src='image/render.png' style='max-width:120px;'></a>"
		."</td></tr></table>"
		."(left click-hold = rotate, right click pan, middle wheel zoom )<br>"
		."So Any voxel that can be download from this site, can be viewed as a point cloud if wanted.<br>"
		."In the voxel download section there are render image/links for each download to click on for 3d viewer.<br><br><br><br>"
		."***New site addition: Image Gallery has been added to the right to house cute little images I have from modding or what ever I want...<br><br><br><br>"
		."***New site addition: Mod called: Specifications Eliminated Warfare: Version 1.0<br>This is a very simple mod that removes country specifications, along with a few other changes.<br><br><br><br>"
		."***New site addition: Left sidebar had some work done to inlude pages for more Ra2/YR maps, along with category selection for the voxel section.<br><br>"
		."I have also released two new maps.<br>"
		."<img src='maps/mini/situation.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/aqua.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section.<br>"
	,"Max McGrath","December 2015","I have Released 9 Voxel Packs, containing 49 voxels.<br>There located in the vxl section on this site, in the other category.<br>"
		."<table><tr>"
		."<td>Civilian Vehicles VXL Pack #2</td>"
		."<td>Holly-Weird VXL pack #3</td>"
		."<td>Military Vehicles VXL pack #1</td>"
		."</tr><tr>"
		."<td valign='top'><img src='vxl/image/civipack3.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/hollyweirdpack3.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/miltpack.png' style='max-width:250px;'></td>"
		."</tr><tr>"
		."<td>Civilian Aircraft VXL Pack #1</td>"
		."<td>Civilian Aircraft VXL Pack #2</td>"
		."<td>Civilian work vehicles VXL Pack #3</td>"
		."</tr><tr>"
		."<td valign='top'><img src='vxl/image/plane1.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/plane2.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/snowvehic.png' style='max-width:250px;'></td>"
		."</tr><tr>"
		."<td>Civilian Naval VXL Pack #1</td>"
		."<td>Military Naval VXL pack #1</td>"
		."<td>Military Vehicles VXL pack #2</td>"
		."</tr><tr>"
		."<td valign='top'><img src='vxl/image/subpack.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/transporpack.png' style='max-width:250px;'></td>"
		."<td valign='top'><img src='vxl/image/truckpack.png' style='max-width:250px;'></td>"
		."</tr></table>"
	,"Max McGrath","November 2015","I have Released 6 Voxel Packs.<br>There located in the vxl section on this site, in the other category.<br>"
		."<table><tr>"
		."<td>Holly-Weird VXL pack #2</td>"
		."<td>Battlestar Galactica voxel pack</td>"
		."</tr><tr>"
		."<td><img src='vxl/image/hollyweirdpack2.png' style='max-width:350px;'></td>"
		."<td><img src='vxl/image/bsg.png' style='max-width:350px;'></td>"
		."</tr><tr>"
		."<td>Civilian work vehicles VXL Pack #1</td>"
		."<td>Civilian work vehicles VXL Pack #2</td>"
		."</tr><tr>"
		."<td><img src='vxl/image/civipack1.png' style='max-width:350px;'></td>"
		."<td><img src='vxl/image/civipack2.png' style='max-width:350px;'></td>"
		."</tr><tr>"
		."<td>Emergency vehicle VXL Pack</td>"
		."<td>Race car VXL Pack</td>"
		."</tr><tr>"
		."<td><img src='vxl/image/emcpack.png' style='max-width:300px;'></td>"
		."<td><img src='vxl/image/race.png' style='max-width:300px;'></td>"
		."</tr></table>"
	,"Max McGrath","November 2015",
		"<img src='maps/pack/mappack1.png'><br>"
		."For your convenience you can download 100 from the Yuri's Revenge map section with one click!<br>"
		."Go to the Yuri Map section to download them all!"
		."<br><br>"
		."Map pack also includes these 4 new maps!<br>"
		."<img src='maps/mini/laced.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/twoocean.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/batchawana.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/inland.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","October 2015","I have Released 4 Voxel Packs.<br>There located in the vxl section on this site, in the other category.<br>"
		."<table><tr>"
		."<td>Mad Max Fury Road Voxel Pack.</td>"
		."<td>A Civilian Vehicles voxel pack.</td>"
		."</tr><tr>"
		."<td><img src='vxl/image/furyroad.png' style='max-width:350px;'></td>"
		."<td><img src='vxl/image/civiveh01.png' style='max-width:350px;'></td>"
		."</tr><tr>"
		."<td>A Farm Vehicles VXL Pack.</td>"
		."<td>A Monster Truck VXL Pack.</td>"
		."</tr><tr>"
		."<td><img src='vxl/image/farmpack01.png' style='max-width:350px;'></td>"
		."<td><img src='vxl/image/monsterpack01.png' style='max-width:350px;'></td>"
		."</tr></table>"
		."<br><br>I also have released 3 halloween themed Ra2/YR maps.<br>"
		."All three maps are meant to be a little silly, Oil derricks given to players at start Map fully revealed."
		."<br>Some give free units like t-rex/mummys ...you get the idea<br>"
		."<img src='maps/mini/jack.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/bat.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/ghost.png' style='width:100px;height:100px;'>"
		."<br><br>I also have released 4 new Ra2/YR maps, and 1 rework.<br>"
		."<img src='maps/mini/dune.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/lawrence.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/melah.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/woods.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/heptagon.png' style='width:100px;height:100px;'>"
		."<br>You can download the maps from the Yuri's Revenge map section."
	,"Max McGrath","September 2015","I have released 10 new Ra2/YR maps, and 1 rework.<br>"
		."<img src='maps/mini/isabella.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/fact.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/belt.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/bigtown.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/channel.png' style='width:100px;height:100px;'>"
		."<br>"
		."<img src='maps/mini/nada.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/tyrrhenian.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/nova.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/ceram.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/ridgecarnagev2.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/frost.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","September 2015","I have created a Tiberian Sun map section. Released 7 maps.<br>"
		."<img src='maps/mini/tsrift.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/trouble.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/tspyro.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/tswreck.png' style='width:100px;height:100px;'>"
		."<br>"
		."<img src='maps/mini/tskodiak.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/tstibpit.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/mission.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Tiberian Sun map section."
	,"Max McGrath","August 2015","I have released 9 new maps.<br>"
		."<img src='maps/mini/isles.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/exhausted.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/edge.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/apex.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/faced.png' style='width:100px;height:100px;'>"
		."<br>"
		."<img src='maps/mini/oblong.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/oppidan.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/mag.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/clover.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","July 2015","HollyWeird vxl Pack 1!<br>"
		."<img src='vxl/image/holyweird1.png' style='max-width:400px;'>"
		."<br>"
		."There located in the vxl section on this site, in the other category."
		."<br><br>"
		."I have also released 8 new maps.<br>"
		."<img src='maps/mini/cabana.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/carnage.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/sand.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/duel.png' style='width:100px;height:100px;'>"
		."<br>"
		."<img src='maps/mini/plateau.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/pyro.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/whitehouse.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/zero.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","July 2015","I have released 14 new maps. Some are remakes from Red Alert 1.<br>"
		."<img src='maps/mini/strength.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/havencon.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/grass.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/pond.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/middle.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/volcano.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/square.png' style='width:100px;height:100px;'>"
		."<br>"
		."<img src='maps/mini/ivory.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/sleepy.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/noman.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/marooned.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/hazard.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/spiral.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/mechanical.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","June 2015","My old mod Ra2 madness has been located and put on this site. Enjoy!"
	,"Max McGrath","June 2015","HA! I have added a bunch more crap!<br>"
		."I went looking through all my old files and said why the hell not...<br>"
		."Most if not all the shps are incomplete...<br>"
		."27 shps...<br>"
		."22 vxls...<br>"
		."4 terrain things... tem/des not complete.<br>"
		."<br>I have also release 7 more maps. Some are older maps that I just never released...<br>"
		."<img src='maps/mini/hostility.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/pentagon.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/infinity.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/arazona.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/libritymini.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/stadium.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/big.png' style='width:100px;height:100px;'>"
	,"Max McGrath","May 2015","I have released 7 new small tournament style maps for Yuri's Revenge.<br>"
		."<img src='maps/mini/deluge.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/rift.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/ridge.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/canal.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/dune.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/triad.png' style='width:100px;height:100px;'>&nbsp;"
		."<img src='maps/mini/rapid.png' style='width:100px;height:100px;'>"
		."<br>You can download them from the Yuri's Revenge map section."
	,"Max McGrath","Summer 2015","Site under construction"
);

//&#x25B2 up &#x25BC down &#9668; left &#9658; right
for($x=0;$x!=count($news);$x+=3){
	if($x>0){
		//echo '<br>';
	}
	echo '<table class="newsblockheader" align="center">'
			. '<tr>'
				. '<td class="newsheader" style="cursor: pointer;" onclick="newsOpen' . $x . '()">'
					. '<div id="blockHeader' . $x . '" name="blockHeader' . $x . '" >'
						. '<span style="float: left;">'
						. 'Posted By: ' . $news[$x] . ' Date: ' . $news[$x+1]
						. '</span>'
						. '<span style="float: right;">&#9668;Click Bar To Open/Close News Block&nbsp;&nbsp;</span>'
					. '</div>'
				. '</td>'
			. '</tr>'
		. '</table>'
		. '<table class="newsblockbody" align="center">'
			. '<tr>'
				. '<td class="newsbody">'
					. '<div id="blockNews' . $x . '" name="blockNews' . $x . '">'
					. '</div>'
					. '<script> var newsChunk' . $x . ' = "' 
						. $news[$x+2]
					. '";'
					. 'var blockNewsOpen' . $x . '=false;'
					. 'function newsOpen' . $x . '(){'
						. 'if(blockNewsOpen' . $x . '){'
							. 'blockNewsOpen' . $x . '=false;'
							. 'document.getElementById("blockNews' . $x . '").innerHTML="";'
						. '}else{'
							. 'blockNewsOpen' . $x . '=true;'
							. 'document.getElementById("blockNews' . $x . '").innerHTML=newsChunk' . $x . ';'
						. '}'
					. '}'
					/* . 'document.getElementById("blockNews' . $x . '").innerHTML = newsChunk' . $x . ';' */
					. '</script>'
				. '</td>'
			. '</tr>'
		. '</table>';
}

//this opens some of the news blocks
echo '<script>';
$numberOfNewToShow = 2;
for($x=0 ; $x != ($numberOfNewToShow * 3) ; $x += 3){
	echo 'blockNewsOpen' . $x . '=true;';
	echo 'document.getElementById("blockNews' . $x . '").innerHTML=newsChunk' . $x . ';';
}
echo '</script>';

?>