<?php

$fileName="grave_SEWcounter.txt";

$file = fopen($fileName, "r");
$value=fread($file,filesize($fileName));
fclose($file);

echo '<table class="newsblockheader" align="center">'
		. '<tr>'
			. '<td class="newsheader">'
				. '**(page under construction)** Specifications Eliminated Warfare: Release Date: December 2015 **(page under construction)**'
				.'<div style="float: right;">'.$value.'</div>'
			. '</td>'
		. '</tr>'
	. '</table>'
	. '<table class="newsblockbody" align="center">'
		. '<tr>'
			. '<td class="newsbody">'
				. 'Red Alert 2: Yuris Revenge<br>Specifications Eliminated Warfare: Version 1.0<br>'
				. '<br>This is a very simple mod that removes country specifications, along with a few other changes.<br>'
				. 'Full change log bellow.<br>'
				. '<br>Required to play: factory Red Alert 2: Yuri\'s Revenge.<br>'
				. 'To install mod, unpack .zip file and add contents to ra2/yr directory.<br>'
				. '<br>Faction Unit Tech Tree<br>'
				. '<table style="width:10%;" align="center"><tr><td>Allies</td><td>Soviets</td><td>Yuri</td></tr><tr><td valign="top">'
				. '<img src="sew/aunittech.png" style="max-width:250px;">'
				. '</td><td valign="top">'
				. '<img src="sew/sunittech.png" style="max-width:250px;">'
				. '</td><td valign="top">'
				. '<img src="sew/yunittech.png" style="max-width:250px;">'
				. '</td></tr></table>'
				. '<br>Faction Building Tech Tree<br>'
				. '<table style="width:10%;" align="center"><tr><td>Allies</td><td>Soviets</td><td>Yuri</td></tr><tr><td valign="top">'
				. '<img src="sew/abuildtech.png" style="max-width:250px;">'
				. '</td><td valign="top">'
				. '<img src="sew/sbuildtech.png" style="max-width:250px;">'
				. '</td><td valign="top">'
				. '<img src="sew/ybuildtech.png" style="max-width:250px;">'
				. '</td></tr></table>'
				. '<br><br>'
				. '<table style="width:10%;" align="center"><tr><td>Tech Secret Lab Units</td><td>Change Log</td></tr><tr><td>'
				. '<img src="sew/civitech.png" style="max-width:250px;">'
				. '</td><td style="text-align:left;width:300px;">'
				. '<div style="width: 500px;height: 200px;overflow: scroll;">'
				. 'Rules change log:'
				. '<br>-Allied country requirements removed for: Americans Paradrop, Sniper, Tank Destroyer, Black Eagle, Grand Cannon.'
				. '<br>-Soviet country requirements removed for: Terrorist, Desolater, Tesla Tank, Demolitions Truck.'
				. '<br>-Resorted and modified Americans Paradrop team for Allies: Consiting of: 6 GI, 4 Navy Seal, 4 Allied Engineer.'
				. '<br>-Added Chrono Commando, Psi-Corp Trooper, Chrono Ivan to Secret Lab Sections Secret Infantry list, to allow better acceces to these units.'
				. '<br>-Allows Force Shield, Chrono Sphere, Iron Curtain, Genetic Mutator to be built\used weither or not super weapons have been disableable from skimish menu.'
				. '<br>-Removed MCVs requirements of Service Depot (Grinder for Yuri) so they can be built straight from weapons factory.'
				. '<br>-Allow transports to be built from weapons factory instead of naval factory.'
				. '<br><br>AI change log:'
				. '<br>-Changed AITriggerTypes in aimd.ini to allow AI to build all contry spacific units.'
				. '<br><br>String change log:'
				. '<br>-Changed the strings: America to Allies, and Russia to Soviets in ra2md.csf.'
				. '<br><br>Graphics change log:'
				. '<br>-Changed Allies, Soviet, Yuri Skermish menu flags to just logos.'
				. '<br><br>Other change log:'
				. '<br>-Added empty ea_wwlogo.bik file to remove EA\Westwood logo.'
				. '</div>'
				. '</td></tr></table>'
				. '<script>function counter(){window.open("http://zombapro.ppmsite.com/grave_counter.php","_blank");}</script>'
				. '<br><br><a href="sew/yr_sew.zip" style="color:red;font-size:30px;" onclick="counter()" download>'
				. 'Click Here To Download'
				. '</a>'
			. '</td>'
		. '</tr>'
	. '</table>';

?>