<?php

//"Max McGrath","Summer 2018","You have been detected as a mobile user."

$news=array(

	"Max McGrath","Summer 2015","Welcome to my graveyard.<br>Do not expect new content, I took a web scripting class and wanted some thing to practice with."
		."<br>If you encounter a problems with the new site you can try to email me at MadHQ04@gmail.com."

	,"Max McGrath","December 2018","I have released 5 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/bifoldret.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/deviltrig.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/hill192.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/quinbarr.jpg'>"
		. "<img class='mapSize' src='maps/minij/snowman.jpg'>"
		. "<br>They are on the 3rd page of the Yuri\'s Revenge maps."

	,"Max McGrath","November 2018","It took me 3 years to complete another 100 Yuri\'s Revenge maps, but I have finally accomplished another 100 maps."
		. "<br><img src='maps/pack/mappack02.png'>"
		. "<br>You can download the 2nd 100 map pack on the 2nd page of Yuri\'s Revenge maps."
		. "<br><br>I have released the final 5 maps for this wave.<br>"
		. "<img class='mapSize' src='maps/minij/bunybowl.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/citytoil.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/metroheight.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/shredder.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/yamantau.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","Spooky Time 2018","Happy Halloween!!!<br>"
		. "I have released 4 spooky themed maps for your enjoyment!<br>"
		. "<img class='mapSize' src='maps/minij/eyes.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/baphomet.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/jason.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/dustybones.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","September 2018","About a year ago I was experimenting with Blender and how well it could render sprites for RA2.<br>I was attempting to make some simple statues."
		. " I was not to happy with the results, I am guessing<br> the problem was due to my lack of 3d or Blender skills. But I guess someone could try to use them, if they wanted.<br>"
		. "There are no damage frames, so just make them explode after one hit.<br>"
		. "<table class='smallTable'><tr><td>"
			. "Statue doodads pack 01<br><img class='newsImgSiz' src='shp/imgjpg/cgmoia.jpg'>"
		. "</td><td>"
			. "Statue doodads pack 02<br><img class='newsImgSiz' src='shp/imgjpg/cgothrst.jpg'>"
		. "</td></tr><tr><td>"
			. "Statue doodads pack 03<br><img class='newsImgSiz' src='shp/imgjpg/cgpeplst.jpg'>"
		. "</td><td>"
			. "Statue doodads pack 04<br><img class='newsImgSiz' src='shp/imgjpg/cgtiki.jpg'>"
		. "</td></tr></table><br>"
		. "Also, a few years ago I took part in a Shape 2 hour tower competition. This is what I created.<br>"
		. "This was never 100% complete, it is missing snow frames, but it should be usable.<br>"
		. "<img class='newsImgSiz' src='shp/imgjpg/casptrdr.jpg'>"
		. "<br><br>Sprites can be found in the Shape page"

	,"Max McGrath","August 2018","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/litmer.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/arisup.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/puzpen.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/midnsp.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","July 2018","I have released 4 new maps based on a maps from C&C 4.<br>"
		. "<img class='mapSize' src='maps/minij/losvall.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/hauptsta.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/withfrac.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/icycell.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","June 2018","This site has been up and decently active for about 3 years,"
		. " and the site has changed and grown alot over those 3 years. In that time<br>all the PHP scripts that generates"
		. " this site are usually hacked and slashed quite a bit to make the changes I desired. So, I decided<br>it would be a good idea to optimize/clean"
		. " this site and the PHP scripts.<br><br>The changes I have made are as follows:<br>Reduced/simplified the amount of concatenation PHP has to deal with<br>Uniformed the HTML layouts for each page<br>"
		. "Most images are now .jpg files for reduced load time<br>Reduced HTML markup on the site layout<br>Improved and fixed some of the site functionality<br>Simplified the sites styles"
		. "<br><br>This cleansing was pretty much a complete overhaul of the site that took about 2 weeks.<br>I am not sure everything is complete or 100% bug free.<br>"
		. "So, if you encounter any problems please let me know."
		. "<br><br><br>I have also released 14 new voxels. These voxels have been sitting on my hard drive for over a year."
		. "<br>I always meant to finish them, but never had an interest in doing so. I figured it was best to just release them as is."
		. "<br><img class='newsImgSiz' src='vxl/imgjpg/voxelsjun.jpg'>"
		. "<br>All the voxels are located on the VXL page."

	,"Max McGrath","May 2018","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/akhiok.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/chankliut.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/easterisl.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/woody.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","April 2018","I am happy to announce my Shape Canvas Painter has hit version 2.0!<br>"
		. "Why is this a big deal? For you? not much, other than faster load times.<br>"
		. "What caused V2.0? No more PHP used! Originally PHP echo all data to the browser in a large string.<br>"
		. "This Shape viewer now retrieves the ZIP file, and reads through the data via the client with javascript.<br><br>"
		. "** Note - Developed and intended for Chrome Browser, other browser results will very.<br><br>"
		. '<a href=\"#\" onclick=\"window.open(\'shapedraw/shpveiw.html?zipName=demo.zip\', \'newwindow\', \'width=500, height=575\'); return false;\">'
		. "Shape Canvas Painter<br><img src='image/canvas2.png'>"
		. "<br>(Opens in new pop-up window)</a><br><br>"
		. "Since I have release Red Alert 2 Alliances: Version 1/4, I can release some of updates I did on a few of my unfinished SHP resources.<br>"
		. "Below lists the resources I have updated. You can download them from the SHP page.<br><br>"
		. "<table class='smallTable'><tr><td>Allied AA Gun</td><td>Allied Base Expansion</td></tr>"
		. "<tr><td>Allied Machine Gun Tower</td><td>Allied Ore Generator</td></tr>"
		. "<tr><td>Allied Naval Sonic Turret</td><td>Allied Subpen</td></tr>"
		. "<tr><td>Allied Tank Bunker</td><td>Allied Weather Tower</td></tr></table>"

	,"Max McGrath","March 2018","Red Alert 2 Alliances: Version 1/4 Released<br>"
		. '<br>Release 1/4 includes the four Allied Alliances<br>'
		. 'This goal of this mod is to try and use all resources found on this site.<br><br>'
		. "<img class='newsImgSiz' src='alliances/map.gif'>"
		. "<br>A link to the Ra2 Alliances page has been added to the left side bar.<br>"

	,"Max McGrath","August 2017","He who lived the past, owns the past.<br>"
		. "<img class='mapSize' src='maps/minij/terrimp.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/hckfreovr.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/apthbynd.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/tralprk.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","July 2017","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/pacfrim.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/icypnch.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/divconq.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/eaglislnd.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","May 2017","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/costinfl.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/eriond.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/forsawast.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/tundtro.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","April 2017","I have released 16 new Civilian voxels!<br>"
		. "A handful are shown below.<br>"
		. "<img src='vxl/imgjpg/scihovr05.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/scihovr09.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/scihovr18.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/scihovr29.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/scihovr30.jpg'>"
		. "<br>All the voxels are located in the VXL page."

	,"Max McGrath","March 2017","I have released 6 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/spratlyis.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/cubcomb.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/yinyang.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/aridmit.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/trumpnation.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/centquad.jpg'>"
		. "<br>They are located on the 2nd page of the Yuri\'s Revenge maps."

	,"Max McGrath","February 2017","I have released 18 new Civilian voxels!<br>"
		. "A handful are shown below.<br>"
		. "<img src='vxl/imgjpg/fcciv09.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv11.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv02.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv05.jpg'><br>"
		. "<img src='vxl/imgjpg/fcciv03.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv12.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv13.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/fcciv16.jpg'><br>"
		. "<br>All the voxels are located in the VXL page."

	,"Max McGrath","January 2017","A new year! New Stuff!<br>"
		. "I am proud to announce my voxel viewer has hit version 2!<br>"
		. "This version uses the games VPL and normal data with alarming similarities to light and shade the voxel.<br>"
		. "<img src='image/voxelveiwV2.png'><br>"
		. "The HVA locations are still not correct, however most are close enough.<br>"
		. "Most features from the old versions have been removed, such as: animations/zoom/panning.<br>"
		. "Another feature of this version that I am proud of is the binary reading of the voxel files is now done locally through javascript.<br>"
		. "Originally, all the data was echoed from PHP, causing unnecessary demands for the host of this site.<br>"
		. "Local processing also decreases the amount of data that is sent.<br><br>"
		. "I have also decided to split all my voxels into individual downloads, bringing the total downloads to 430.<br><br>"
		. "I have also released a handful of new voxels, below shows a few of them.<br>"
		. "<img src='vxl/imgjpg/VEHICZ.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/VEHICT.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/VEHICO.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/mindhand.jpg'><br>"
		. "<img src='vxl/imgjpg/CIVUSHIPC.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/CIVUSHIPB.jpg'><br>"
		. "<img src='vxl/imgjpg/CIVUSHIPE.jpg'>"
		. "<br>All the voxels are located in the VXL page."

	,"Max McGrath","December 2016","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/divide.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/earth.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/paramenides.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/trinity.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","X-mas 2016","Blast from the past! Holiday Edition!<br>"
		. "<img class='newsImgSizLg' src='screen/xmassmodfake.png'><br>"
		. "Many Christmases ago, I was working on a silly X-mas mod for YR.<br>"
		. "This mod failed to finish sadly. However! An Awesome holiday<br>"
		. "soundtrack was made. And this is the 1st time I have ever<br>"
		. "included anyone else\'s work on my site. Soundtrack auther is pd<br><br>"
		. "You can click on a track to listen to any of the songs listed below!"
		. "<table class='smallTable'><tr><td>"
			."<div class='downloadbar' id='audioXmassSet' onclick='openXmasAud()'>Click here to open preview player</div>"
		. "</td></tr><tr><td class='xmasGreen'>"
			. "<div onclick='playAudio(0)'>Track #1 - Snow Falling - creator: pd</div>"
		. "</td></tr><tr><td class='xmasRed'>"
			. "<div onclick='playAudio(1)'>Track #2 - Santaphobia - creator: pd</div>"
		. "</td></tr><tr><td class='xmasGreen'>"
			. "<div onclick='playAudio(2)'>Track #3 - Unpack Your Present - creator: pd</div>"
		. "</td></tr><tr><td class='xmasRed'>"
			. "<div onclick='playAudio(3)'>Track #4 - The Turkeys Last Dance - creator: pd</div>"
		. "</td></tr><tr><td class='xmasGreen'>"
			. "<div onclick='playAudio(4)'>Track #5 - The Elve Song - creator: pd</div>"
		. "</td></tr><tr><td class='xmasRed'>"
			. "<div onclick='playAudio(5)'>Track #6 - Heavy Christmas - creator: pd</div>"
		. "</td></tr><tr><td class='xmasGreen'>"
			. "<div onclick='playAudio(6)'>Track #7 - Lazy Claus - creator: pd</div>"
		. "</td></tr><tr><td class='xmasRed'>"
			. "<div onclick='playAudio(7)'>Track #8 - Toy Factory - creator: pd</div>"
		. "</td></tr></table>"
		. "<br>You can find a link to download a zip of all tracks in the Audio section."

	,"Max McGrath","November 2016","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/plush.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/arctictwist.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/chilled.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/iceage.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","November 2016","Debris Maker Version 1.0 Released!!<br><br>"
		. "<table class='smallTable'><tr><td>I have released version 1.0 of my javascript application Debris Maker."
		. "<br>I have released this as I feel it is complete enough for others to use."
		. "<br>Please read the information about the editer before useing."
		. "<br>If you encounter any errors please notify me."
		. "</td><td><img class='newsImgSiz' src='tools/debris/images/debris00.png'></td></tr></table>"
		. "<br>A link to the Debris Maker is located in the left side bar."

	,"Max McGrath","November 2016","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/vicircuit.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/hamlet.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/squid.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/dolphin.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","November 2016","VPL Editor Version 1.0 Released!!<br><br>"
		. "<table class='smallTable'><tr><td>I have released version 1.0 of my javascript application VPL editor. Future versions will"
		. "<br>have voxel loading for the the 3d view, this will be better for visualization of the changes"
		. "<br>made to the vpl data, along with more curve generating features and improvements."
		. "</td><td><img class='smallTable' src='tools/vpleditor/images/vplwheel.png'></td></tr></table>"
		. "<br>A link to the VPL Editor is located in the left side bar."

	,"Max McGrath","Spooky Time 2016","Happy Halloween!!!<br>"
		. "I have released 4 spooky themed maps for your enjoyment!<br>"
		. "<img class='mapSize' src='maps/minij/witchmap.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/spidermap.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/devilmap.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/grimmap.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","September 2016","A whole new download section!<br>"
		. "For years I have been asked how did I make Ra2/YR buildings, or can I release the 3d models and textures. The reasons I have never wanted"
		. "<br>to, is because my 3d skills are not spectacular, and it would most likely require someone to have the same programs I use, so it just"
		. "<br>seemed kind of point-less. But seeing as I do not care to much any more, and this site is pretty much just a collection of stuff any ways,"
		. "<br>I might as well put them up for download. I have released one building of each faction, so maybe some one can find them helpfull."
		. "<br>And if this is some thing people like, I can release more, if I still have them..."
		. "<br>So take note*** these 3d models will need 3ds max 2013 or newer to open.<br><br>"
		. "<img class='newsImgSiz' src='3dmodels/image/GAWEATHER.png'>&nbsp;"
		. "<img class='newsImgSiz' src='3dmodels/image/NABARX.png'><br>"
		. "<img class='newsImgSiz' src='3dmodels/image/YAPUPET.png'>"
		. "<br>They are located in the 3d model area."

	,"Max McGrath","September 2016","Some more junk heading your way!<br>"
		. "<br>So, I just recently purchased a hard drive to USB adapter thing. This gave me the opportunity to hunt through my now dead desktop"
		. "<br>hard drive. On this drive I found lots of unfinished stuff that I figured I could put up on the site."
		. "<br><br>Starting off this larger then normal news post, is what I hope is the most current version of my Empire Of The Rising Sun mod."
		. "<br>Note** as with most of my stuff it is not complete, but should still be playable."
		. "<br>In the left side bar you should find a link to download the mod and a little info."
		. "<br><img class='newsImgSiz' src='empireMod/empire.png'>&nbsp;"
		. "<br><br><br>Along with the mod I have decided to release all assets from the mod in individual downloads."
		. "<br>The images below show some of resources, and of course not all are finished, but could be usable.<br>"
		. "<img src='shp/imgjpg/eacnyrd.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/eabarx.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/eatch.jpg'><br>"
		. "<img src='shp/imgjpg/yuriko.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/ninja.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/rctangl.jpg'><br>"
		. "<img src='shp/imgjpg/sidec04.jpg'>"
		. "<br><br><br>Up next is some terrain sets that I was working on. None were 100% finished but could be used"
		. "<br>if someone is clever enough. This news post only shows 2 of the 4 sets.<br>"
		. "<img src='shp/imgjpg/legotemp.jpg'>&nbsp;"
		. "<img class='newsImgSiz' src='shp/imgjpg/float.jpg'>"
		. "<br><br><br>Moveing right along, there are some more voxels added to the site."
		. "<br>This news post only shows some of the voxels, there are a few others not shown here.<br>"
		. "<img src='vxl/imgjpg/aqtnk.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/mammy.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/utnk.jpg'><br>"
		. "<img src='vxl/imgjpg/b2.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/humr.jpg'>&nbsp;"
		. "<img src='vxl/imgjpg/enagin.jpg'>"
		. "<br><br><br>Even more junk! Ha! So I have also added a bunch of unfinished buildings and units."
		. "<br>This news post only shows some of the shapes, there are others not shown here.<br>"
		. "<img src='shp/imgjpg/modern.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/gawhtr.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/GGREFNX.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/naion.jpg'><br>"
		. "<img src='shp/imgjpg/nabarx.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/bear.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/naweap2.jpg'>&nbsp;"
		. "<img src='shp/imgjpg/ngcybcr.jpg'>"
		. "<br><br><br>And now finally, I have released three more maps. I am always happy to add more maps to my largely growing collection.<br>"
		. "<img class='mapSize' src='maps/minij/junglebasin.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/valleydeath.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/credit.jpg'>"
		. "<br><br>I also found and added some more images to the gallery.<br>By now you should be able to find this crap."

	,"Max McGrath","September 2016","A little blast from my past!<br>"
		. "While cleaning my apartment I found an old flash drive I used for back-up. So I investigated what was on it.<br>"
		. "Now, there was not too much, or really anything of value. However, I figure I can release whatever I want.<br>"
		. "<br>There was 5 maps (all of which I had to make a lazy attempt to finish).<br>"
		. "<img class='mapSize' src='maps/minij/marland.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/dcolombia.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/skullis.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/soviet.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/circaljerk.jpg'><br>"
		. "<br>There was also 2 voxels that I thought I had lost (Two Renegade conversions)."
		. "<table class='smallTable'><tr><td>"
			. "Renegade Orca<br><img src='vxl/imgjpg/renorca.jpg'>"
		. "</td><td>"
			. "Renegade Humvee<br><img src='vxl/imgjpg/renhummer.jpg'>"
		. "</td></tr></table>"
		. "<br>There was also a few unfinished shp's, and there was a collection of map doodad things."
		. "<table class='smallTable'><tr><td>"
			. "Orc Unit<br><img src='shp/imgjpg/orcinfy.jpg'>"
		. "</td><td>"
			. "GDI Infantry<br><img src='shp/imgjpg/gdiinfy.jpg'>"
		. "</td><td>"
			. "Nod Infantry<br><img src='shp/imgjpg/nodinfy.jpg'>"
		. "</td></tr></table>"
		. "<table class='smallTable'><tr><td>"
			. "Doodad Things<br><img class='newsImgSiz' src='shp/imgjpg/oddpack01.jpg'>&nbsp;"
		. "</td><td>"
			. "GDI Cannon<br><img src='shp/imgjpg/tscannon.jpg'>"
		. "</td></tr></table>"
		. "<br>The flash drive also contains audio sets for two units I record for one of Allied General mods.<br>"
		. "The mod is long since gone and dead, so I might as well put them here for a laugh.<br>"
		. "I created a audio section in the left sidebar other section if you want to listen/laugh/download, the recording is not great.<br>"
		. "I have added 3 wav files of each set to this news post, there are more in the audio section."
		. "<br><br>MadHQ<br><div class='smallTable'><div class='audioBox' id='MadHQAud' onclick='openMadHQAud()'>Click here to open player</div></div>"
		. "<br><br>Zomba<br><div class='smallTable'><div class='audioBox' id='ZombaAud' onclick='openZombaAud()'>Click here to open player</div></div>"
		. "<br><br>I also found and added some more images to the gallery.<br>By now you should be able to find this crap."

	,"Max McGrath","September 2016","I have released 4 new maps.<br>"
		. "For fun, I have recorded speed builds of each map, click a minmap to watch (YouTube link opens in new window/tab).<br>"
		. "<a href='https://www.youtube.com/watch?v=IvTmfWsgkYw' target='_blank'><img class='mapSize' src='maps/minij/company.jpg'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=2EuuhOCioho' target='_blank'><img class='mapSize' src='maps/minij/desometro.jpg'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=g9hc0HLgKo4' target='_blank'><img class='mapSize' src='maps/minij/theseam.jpg'>&nbsp;</a>"
		. "<a href='https://www.youtube.com/watch?v=mrRe290TbVM' target='_blank'><img class='mapSize' src='maps/minij/sextuplet.jpg'></a>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","August 2016","I have released 4 new maps. Probably not usable with other mods.<br>"
		. "Now these maps are a little odd... Every once in a wail I like to do some thing different.<br>"
		. "In this case, these maps spawn lots of neutral units that move across the map.<br>"
		. "<img class='mapSize' src='maps/minij/roadrage.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/virginmoscow.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/toarc.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/autodown.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","July 2016","I have released 6 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/nora.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/mirageshock.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/dahlac.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/kongsoya.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/abeloya.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/coburg.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","June 2016","I have released 6 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/bloodreef.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/aegean.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/rockysurf.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/santorini.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/agattu.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/tokashiki.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","June 2016","I have released 3 new maps.<br>I have also released 7 chopped maps for fun.<br>"
		. "<img class='mapSize' src='maps/minij/carhift.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/terplant.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/portroy.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/midrap.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/fairgro.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/branboon.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/cenelev.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/normetro.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/nublar.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/downtown.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","March 2016","I have released 6 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/encroachment.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/pipe.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/bowtie.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/frostedreft.jpg'><br>"
		. "<img class='mapSize' src='maps/minij/straight.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/dustava.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","March 2016","I have released 4 new maps.<br>"
		. "<img class='mapSize' src='maps/minij/halo.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/pubcom.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/duscan.jpg'>&nbsp;"
		. "<img class='mapSize' src='maps/minij/civvio.jpg'>"
		. "<br>They are on the 2nd page of map area."

	,"Max McGrath","February 2016","If you noticed or care, I have been making changes/fixes all over the place to this site.<br>"
		. "If you find any problems please let me know.<br><br>"
		. "Anyways, I Released three more Doodad Voxel Packs.<br><br>"
		. "<table class='smallTable'><tr><td>"
			. "Civilian Work Vehicles VXL Pack #5<br><img class='newsImgSiz' src='vxl/imgjpg/civiwrkpack05.jpg'>"
		. "</td><td>"
			. "Civilian Work Vehicles VXL Pack #7<br><img class='newsImgSiz' src='vxl/imgjpg/civiwrkpack07.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian Work Vehicles VXL Pack #6<br><img class='newsImgSiz' src='vxl/imgjpg/civiwrkpack06.jpg'>"
		. "</td><td>"
			. "I have also released 2 new maps<br>"
			. "<img class='mapSize' src='maps/minij/triplication.jpg'>&nbsp;"
			. "<img class='mapSize' src='maps/minij/pinch.jpg'>"
		. "</td></tr></table>"
		. "<br>Voxels are in other category in voxel section, and the maps are on the 2nd page of map area."

	,"Max McGrath","February 2016","Released three more Doodad Voxel Packs.<br>"
		. "<table class='smallTable'><tr><td>"
			. "Civilian Ship Voxel Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/shippack03.jpg'>"
		. "</td><td>"
			. "Civilian Ship Voxel Pack #4<br><img class='newsImgSiz' src='vxl/imgjpg/shippack01.jpg'>"
		. "</td></tr><tr><td colspan='2'>"
			. "Civilian Ship Voxel Pack #3<br><img class='newsImgSiz' src='vxl/imgjpg/shippack02.jpg'>"
		. "</td></tr></table>"
		. "<br>Voxels are in other category in voxel section."

	,"Max McGrath","February 2016","Released two more Doodad Voxel Packs.<br><br>"
		. "Holly-Weird VXL pack #4<br><img class='newsImgSiz' src='vxl/imgjpg/hollyweird4.jpg'>"
		. "<br><br>Civilian Van Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/civivanpack.jpg'>"
		. "<br>Voxels are in other category in voxel section."

	,"Max McGrath","January 2016","I am really proud to showcase a new feature to this site. This feature is a .shp file viewer through HTML5 canvas.<br>"
		. "Though it is still very much W.I.P.,"
		. "So far it seems stable enough to build into this site.<br>Click the image bellow to view demo Ra2/Yr .shp files in viewer.<br><br>"
		. "Shape Canvas Painter<br>"
		. "<a href='shapedraw/drawshape.php?zipName=demo.zip&fileName=cons.shp' target='_blank'>"
		. "<img src='image/canvas.png'>"
		. "<br>(Opens in new window/tab)</a>"
		. "<br><br>Now, there is sill much to do, such as:<br>animations, terrain (tiles,trees,cliff...), maybe another shp format compression., maybe look into some kind of pallet solution..."
		. "<br><br>This viewer is built into the SHP section of this site exactly like the Voxel viewer is.<br>"
		. "I have omitted a few sph files/downloads, as the viewer is not ready for them."
		. "<br>Other wise have fun and let me know if you experience any problems."

	,"Max McGrath","January 2016","Well seeing as this site is still growing and I am still hanging around, I felt as though I needed to add a few things.<br>"
		. "First: I have created a Permissions page that talks about permissions and legal crap.<br>"
		. "Second: I have created a F.A.Q. page as I get a lot of similar questions."
		. "<br><br>Moving on to something more pleasant...<br>This is the last of the assets I was working on for my modded missions.<br>"
		. "I thought it would be best to touch them up a little more before releasing them.<br><br>"
		. "<table class='smallTable'><tr><td>"
			. "Civilian Work Vehicles Voxel Pack #4<br><img class='newsImgSiz' src='vxl/imgjpg/civipack04.jpg'>"
		. "</td><td>"
			. "Civilian Ship Voxel Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/ship01.jpg'>"
		. "</td></tr></table>"
		. "<br>Voxels are in other category in voxel section."

	,"Max McGrath","January 2016","Well I am giving up on a modded mission pack project I was working on. Ended up being too much work.<br>"
		."So I am just going to release things as they are. Not everything is complete what you see is pretty much it.<br>I am doing this because I want to spend more time "
		."playing with html5 stuff.<br><br>"
		. "<table class='smallTable'><tr><td>"
			. "Sport Car Voxel Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/sportpack01.jpg'>"
		. "</td><td>"
			. "Sport Car Voxel Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/sportpack02.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian Pickup Truck Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/truckpack01.jpg'>"
		. "</td><td>"
			. "Civilian Pickup Truck Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/truckpack02.jpg'>"
		. "</td></tr><tr><td>"
			. "Boot Camp Doodad Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/bootcamppack.jpg'>"
		. "</td><td>"
			. "Tables Doodad Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/tablepack1.jpg'>"
		. "</td></tr><tr><td>"
			. "Vending Machine Doodad Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/vendingpack.jpg'>"
		. "</td><td>"
			. "Fair Ride Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/fairpack1.jpg'>"
		. "</td></tr><tr><td>"
			. "Wild West Doodad Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/westbitspack.jpg'>"
		. "</td><td>"
			. "Wild West Building Pack #1<br><img class='newsImgSiz' src='shp/imgjpg/westbuildpack01.jpg'>"
		. "</td></tr><tr><td>"
			. "Wild West Building Pack #2<br><img class='newsImgSiz' src='shp/imgjpg/westbuildpack02.jpg'>"
		. "</td><td>"
			. "Wild West Building Pack #3<br><img class='newsImgSiz' src='shp/imgjpg/westbuildpack03.jpg'>"
		. "</td></tr></table>"
		. "<br>Sprites can be found in shp section, voxels are in other category in voxel section."

	,"Max McGrath","January 2016","Aw, SNAP! new assets even in this very new year!<br>Lets start the new year with some FUN!<br><br>"
		. "Collection of simple Mario Kart sprites.<br>"
		. "<img class='newsImgSizLg' src='shp/imgjpg/mario.jpg'><br><br>"
		. "<table class='smallTable'><tr><td>"
			. "S.W.A.T Voxel Pack<br><img class='newsImgSiz' src='vxl/imgjpg/swat.jpg'>"
		. "</td><td>"
			. "Civilian Hummer Voxel Pack<br><img class='newsImgSiz' src='vxl/imgjpg/hummerpack.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian Train Voxel Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/trainpack1.jpg'>"
		. "</td><td>"
			. "Civilian Train Voxel Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/trainpack2.jpg'>"
		. "</td></tr></table>"
		. "<br>Mario sprites can be found in shp section, voxels are in other category in voxel section."

	,"Max McGrath","December 2015","Updates to the site all over the place!<br><br>"
		."***New site feature: I am really proud and excited for is this 3D point cloud render I created.<br>"
		."Note* This is still WORK-IN-PROGRESS so it can be a little buggy... <br>IE. hva locations/animations, turret/barrel have some issues... My 3d viewer still needs more work.<br>"
		."<br>The 3 images below are demo links to official RA2/YR units.<br>"
		. "<table class='smallTable'><tr><td>"
			."Allied Units<br><a href='vxlrender/vxlrender.php?zipName=alliedunits.zip' target='_blank'><img src='image/render.png'></a>"
		."</td><td>"
			."Soviet Units<br><a href='vxlrender/vxlrender.php?zipName=sovietunits.zip' target='_blank'><img src='image/render.png'></a>"
		."</td><td>"
			."Yuri Units<br><a href='vxlrender/vxlrender.php?zipName=yuriunits.zip' target='_blank'><img src='image/render.png'></a>"
		."</td></tr></table>"
		."(left click-hold = rotate, right click pan, middle wheel zoom )<br>"
		."So Any voxel that can be download from this site, can be viewed as a point cloud if wanted.<br>"
		."In the voxel download section there are render image/links for each download to click on for 3d viewer.<br><br>"
		."***New site addition: Image Gallery has been added to the right to house cute little images I have from modding or what ever I want...<br><br>"
		."***New site addition: Mod called: Specifications Eliminated Warfare: Version 1.0<br>This is a very simple mod that removes country specifications, along with a few other changes.<br><br>"
		."***New site addition: Left sidebar had some work done to inlude pages for more Ra2/YR maps, along with category selection for the voxel section.<br><br>"
		."I have also released two new maps.<br>"
		."<img class='mapSize' src='maps/minij/situation.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/aqua.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","December 2015","I have Released 9 Voxel Packs, containing 49 voxels.<br>There located in the vxl section on this site, in the other category.<br>"
		. "<table class='smallTable'><tr><td>"
			. "Civilian Vehicles VXL Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/civipack3.jpg'>"
		. "</td><td>"
			. "Holly-Weird VXL pack #3<br><img class='newsImgSiz' src='vxl/imgjpg/hollyweirdpack3.jpg'>"
		. "</td></tr><tr><td>"
			. "Military Vehicles VXL pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/miltpack.jpg'>"
		. "</td><td>"
			. "Civilian Aircraft VXL Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/plane1.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian Aircraft VXL Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/plane2.jpg'>"
		. "</td><td>"
			. "Civilian work vehicles VXL Pack #3<br><img class='newsImgSiz' src='vxl/imgjpg/snowvehic.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian Naval VXL Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/subpack.jpg'>"
		. "</td><td>"
			. "Military Vehicles VXL pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/truckpack.jpg'>"
		. "</td></tr><tr><td>"
			. "Military Naval VXL pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/transporpack.jpg'>"
		. "</td><td>"
		. "</td></tr></table>"

	,"Max McGrath","November 2015","I have Released 6 Voxel Packs.<br>There located in the vxl section on this site, in the other category.<br>"
		. "<table class='smallTable'><tr><td>"
			. "Holly-Weird VXL pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/hollyweirdpack2.jpg'>"
		. "</td><td>"
			. "Battlestar Galactica voxel pack<br><img class='newsImgSiz' src='vxl/imgjpg/bsg.jpg'>"
		. "</td></tr><tr><td>"
			. "Civilian work vehicles VXL Pack #1<br><img class='newsImgSiz' src='vxl/imgjpg/civipack1.jpg'>"
		. "</td><td>"
			. "Civilian work vehicles VXL Pack #2<br><img class='newsImgSiz' src='vxl/imgjpg/civipack2.jpg'>"
		. "</td></tr><tr><td>"
			. "Emergency vehicle VXL Pack<br><img class='newsImgSiz' src='vxl/imgjpg/emcpack.jpg'>"
		. "</td><td>"
			. "Race car VXL Pack<br><img class='newsImgSiz' src='vxl/imgjpg/race.jpg'>"
		. "</td></tr></table>"

	,"Max McGrath","November 2015",
		"<img class='newsImgSizLg' src='maps/pack/mappack1.png'><br>"
		."For your convenience you can download 100 from the Yuri's Revenge map section with one click!"
		."<br>Go to the Yuri Map section to download them all!"
		."<br><br>Map pack also includes these 4 new maps!<br>"
		."<img class='mapSize' src='maps/minij/laced.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/twoocean.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/batchawana.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/inland.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","October 2015","I have Released 4 Voxel Packs.<br>There located in the vxl section on this site, in the other category.<br>"
		. "<table class='smallTable'><tr><td>"
			. "Mad Max Fury Road Voxel Pack<br><img class='newsImgSiz' src='vxl/imgjpg/furyroad.jpg'>"
		. "</td><td>"
			. "A Civilian Vehicles voxel pack<br><img class='newsImgSiz' src='vxl/imgjpg/civiveh01.jpg'>"
		. "</td></tr><tr><td>"
			. "A Farm Vehicles VXL Pack<br><img class='newsImgSiz' src='vxl/imgjpg/farmpack01.jpg'>"
		. "</td><td>"
			. "A Monster Truck VXL Pack<br><img class='newsImgSiz' src='vxl/imgjpg/monsterpack01.jpg'>"
		. "</td></tr></table>"
		."<br><br>I also have released 3 halloween themed Ra2/YR maps."
		."<br>All three maps are meant to be a little silly, Oil derricks given to players at start Map fully revealed."
		."<br>Some give free units like t-rex/mummys ...you get the idea<br>"
		."<img class='mapSize' src='maps/minij/jack.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/bat.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/ghost.jpg'>"
		."<br><br>I also have released 4 new Ra2/YR maps, and 1 rework.<br>"
		."<img class='mapSize' src='maps/minij/dune.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/lawrence.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/melah.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/woods.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/heptagon.jpg'>"
		."<br>You can download the maps from the Yuri's Revenge map section."

	,"Max McGrath","September 2015","I have released 10 new Ra2/YR maps, and 1 rework.<br>"
		."<img class='mapSize' src='maps/minij/isabella.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/fact.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/belt.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/bigtown.jpg'><br>"
		."<img class='mapSize' src='maps/minij/channel.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/nada.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/tyrrhenian.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/nova.jpg'><br>"
		."<img class='mapSize' src='maps/minij/ceram.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/ridgecarnagev2.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/frost.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","September 2015","I have created a Tiberian Sun map section. Released 7 maps.<br>"
		."<img class='mapSize' src='maps/minij/tsrift.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/trouble.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/tspyro.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/tswreck.jpg'><br>"
		."<img class='mapSize' src='maps/minij/tskodiak.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/tstibpit.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/mission.jpg'>"
		."<br>You can download them from the Tiberian Sun map section."

	,"Max McGrath","August 2015","I have released 9 new maps.<br>"
		."<img class='mapSize' src='maps/minij/isles.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/exhausted.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/edge.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/apex.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/faced.jpg'><br>"
		."<img class='mapSize' src='maps/minij/oblong.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/oppidan.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/mag.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/clover.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","July 2015","HollyWeird vxl Pack 1!<br>"
		."<img class='newsImgSiz' src='vxl/imgjpg/holyweird1.jpg'>"
		."<br>There located in the vxl section on this site, in the other category."
		."<br><br>I have also released 8 new maps.<br>"
		."<img class='mapSize' src='maps/minij/cabana.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/carnage.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/sand.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/duel.jpg'><br>"
		."<img class='mapSize' src='maps/minij/plateau.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/pyro.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/whitehouse.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/zero.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","July 2015","I have released 14 new maps. Some are remakes from Red Alert 1.<br>"
		."<img class='mapSize' src='maps/minij/strength.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/havencon.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/grass.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/pond.jpg'><br>"
		."<img class='mapSize' src='maps/minij/middle.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/volcano.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/square.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/ivory.jpg'><br>"
		."<img class='mapSize' src='maps/minij/sleepy.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/noman.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/marooned.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/hazard.jpg'><br>"
		."<img class='mapSize' src='maps/minij/spiral.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/mechanical.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","June 2015","My old mod Ra2 madness has been located and put on this site. Enjoy!"

	,"Max McGrath","June 2015","HA! I have added a bunch more crap!<br>"
		."I went looking through all my old files and said why the hell not...<br>"
		."Most if not all the shps are incomplete...<br>"
		."27 shps...<br>"
		."22 vxls...<br>"
		."4 terrain things... tem/des not complete.<br>"
		."<br>I have also release 7 more maps. Some are older maps that I just never released...<br>"
		."<img class='mapSize' src='maps/minij/hostility.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/pentagon.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/infinity.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/arazona.jpg'><br>"
		."<img class='mapSize' src='maps/minij/libritymini.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/stadium.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/big.jpg'>"

	,"Max McGrath","May 2015","I have released 7 new small tournament style maps for Yuri's Revenge.<br>"
		."<img class='mapSize' src='maps/minij/deluge.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/rift.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/ridge.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/canal.jpg'><br>"
		."<img class='mapSize' src='maps/minij/dune.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/triad.jpg'>&nbsp;"
		."<img class='mapSize' src='maps/minij/rapid.jpg'>"
		."<br>You can download them from the Yuri's Revenge map section."

	,"Max McGrath","Summer 2015","Site under construction"
);

?>
