<?php

$shp=array(
	//Allied shps
	"Allied Gun Turret","alligun.jpg","Allied Gun Turret","gagun.zip","1","1","0","0"
	,"Allied Gun Turret","gaguntr.jpg","Allied Gun Turret","gaguntr.zip","1","1","0","0"
	,"Allied Sonic Turret","gasonic.JPG","Allied Sonic Turret","gasonic.zip","1","1","0","0"
	,"Allied Laser Turret","galasr.JPG","Allied Laser Turret","galasr.zip","1","1","0","0"
	,"Allied Spining Gap Gen","gagap.JPG","Allied Spining Gap Gen","gagap.zip","1","1","0","0"
	,"Allied Battle Bunker","gabunk.jpg","Allied Battle Bunker","gabnk.zip","1","1","0","0"
	,"Allied Prossing Plant","gapros.JPG","Allied Prossing Plant","gapros.zip","1","1","0","0"
	,"Allied AA Gun","gaagn.jpg","Allied AA Gun","gaagn.zip","1","1","1","0"
	,"Allied Base Expansion","gabasexpn.jpg","Allied Base Expansion","gabasxpan.zip","1","1","1","0"
	,"Allied Machine Gun Tower","gamngn.jpg","Allied Machine Gun Tower","gamngn.zip","1","1","1","0"
	,"Allied Naval Repair Bay","ganavrepair.jpg","Allied Naval Repair Bay (Not Finished)","ganavrepair1.zip","1","0","0","0"
	,"Allied Ore Generator","gaoregen.jpg","Allied Ore Generator","gaoregen.zip","1","1","1","0"
	,"Allied Naval Sonic Turret","gasonictur.jpg","Allied Naval Sonic Turret (No snow frames, Not needed)","ganasonic1.zip","1","1","1","0"
	,"Allied Subpen","gasubpin.jpg","Allied Subpen","gasubyard.zip","1","1","1","0"
	,"Allied Tank Bunker","gatnkbnk.jpg","Allied Tank Bunker","gatnkbnk.zip","1","1","1","0"
	,"Allied Tower","gatower.jpg","Allied Tower (Not Finished)","gatower.zip","1","0","0","0"
	,"Allied Wall Gates","gawall.jpg","Allied Wall Gates (Not Finished)","gawall1.zip","1","0","0","0"
	,"Allied Weather Tower","gaweather.jpg","Allied Weather Tower (Not Finished)","gaweather.zip","1","0","0","0"
	,"Allied Weather Tower","gawhtr.jpg","Allied Weather Tower","gawhtr.zip","1","1","1","0"
	,"Allied Weapons Factory","GAWEAP3.jpg","Allied Weapons Factory (Not Finished)","GAWEAP3.zip","1","0","0","0"
	,"Allied Barracks","GGBARX.jpg","Allied Barracks (Not Finished)","GGBARX.zip","1","0","0","0"
	,"Allied Construction Yard","GGCONYX.jpg","Allied Construction Yard (Not Finished)","GGCONYX.zip","1","0","0","0"
	,"Allied Radar Dome","GGDOMEX.jpg","Allied Radar Dome (Not Finished)","GGDOMEX.zip","1","0","0","0"
	,"Allied Power Plant","GGPWRX.jpg","Allied Power Plant (Not Finished)","GGPWRX.zip","1","0","0","0"
	,"Allied Refinery","GGREFNX.jpg","Allied Refinery (Not Finished)","GGREFNX.zip","1","0","0","0"
	,"Allied Weapons Factory","GGWEAP2.jpg","Allied Weapons Factory (Not Finished)","GGWEAP2.zip","1","0","0","0"

	//Soviet shps
	,"Soviet Sentry","sovsnty.jpg","Soviet Sentry","nasnty.zip","1","1","0","0"
	,"Soviet Missle Turret","sovmissl.jpg","Soviet Missle Turret","namisltur.zip","1","1","0","0"
	,"Soviet Flame Turret","flametur.jpg","Soviet Flame Turret","naflame.zip","1","1","0","0"
	,"Soviet Tank Bunker","natnkbnk.jpg","Soviet Tank Bunker","natnkbnk.zip","1","1","0","0"
	,"Soviet Airpad","napad.jpg","Soviet Airpad","napadn.zip","1","1","0","0"
	,"Soviet Subpen","nasubpen.JPG","Soviet Subpen","nasubpen.zip","1","1","0","0"
	,"Soviet AA Gun","naaagun.jpg","Soviet AA Gun (Not Finished)","NGAGN.zip","1","0","0","0"
	,"Soviet Hell Cannon","nahlcn.jpg","Soviet Hell Cannon (Not Finished)","nahlcn.zip","1","0","0","0"
	,"Soviet Naval Missle Turret","nanavmistr.jpg","Soviet Naval Missle Turret (Not Finished)","nanavmistr.zip","1","0","0","0"
	,"Soviet Ore Generator","naoregen.jpg","Soviet Ore Generator (Not Finished)","naoregen.zip","1","0","0","0"
	,"Soviet Ore Generator","naorgen.jpg","Soviet Ore Generator (Not Finished)","naorgen.zip","1","0","0","0"
	,"Soviet Ore Generator","naorgen2.jpg","Soviet Ore Generator (Not Finished)(Has Build-up)","naorgen2.zip","1","0","0","0"
	,"Soviet Airpad","napad1.jpg","Soviet Airpad (Not Finished)","napad.zip","1","0","0","0"
	,"Soviet Tech Center","natech.jpg","Soviet Tech Center (Not Finished)","natech.zip","1","0","0","0"
	,"Soviet Tower","natower.jpg","Soviet Tower (Not Finished)","natower.zip","1","0","0","0"
	,"Soviet Red Alert 3 Terror Drone","drone.jpg","Terror Drone","dron.zip","1","0","0","0"
	,"Soviet Terrorist on a Bike","terbik.jpg","Terrorist on a Bike","terbik.zip","1","0","0","0"
	,"Soviet Terrorist on a Jet Ski","terski.jpg","Terrorist on a Jet Ski","terski.zip","1","0","0","0"
	,"Soviet Conscript on a Quad Bike","conwhl.jpg","Conscript on a Quad Bike","conwhl.zip","1","0","0","0"
	,"Cybernetic Bear","bear.jpg","Cybernetic Bear (Not Finished)(not attack frames)","bear.zip","1","0","0","0"
	,"Soviet Barracks","nabarx.jpg","Soviet Barracks (Not Finished)","nabarx.zip","1","0","0","0"
	,"Soviet Ion Cannon","naion.jpg","Soviet Ion Cannon (Not Finished)","naion.zip","1","0","0","0"
	,"Soviet Nuke Silo","nanuke.jpg","Soviet Nuke Silo (Not Finished)","nanuke.zip","1","0","0","0"
	,"Soviet Power Plant","NAPWR2.jpg","Soviet Power Plant (Not Finished)","NAPWR2.zip","1","0","0","0"
	,"Soviet Power Plant","NAPWRX.jpg","Soviet Power Plant (Not Finished)","NAPWRX.zip","1","0","0","0"
	,"Soviet Radar","NARDR.jpg","Soviet Radar (Not Finished)","NARDR.zip","1","0","0","0"
	,"Soviet Weapons Factory","naweap2.jpg","Soviet Weapons Factory (Not Finished)","naweap2.zip","1","0","0","0"
	,"Soviet Cyborg Facility","ngcybcr.jpg","Soviet Cyborg Facility (Not Finished)","ngcybcr.zip","1","0","0","0"
	,"Soviet Air Tower","NAAIRTWR.jpg","Soviet Air Tower (Not Finished)","NAAIRTWR.zip","1","0","0","0"

	//Yuri shps
	,"Yuri Magnetic Tower","yamagtwr.jpg","Yuri Magnetic Tower","yamagtwr.zip","1","1","0","0"
	,"Yuri Battle Bunker","yabunk.jpg","Yuri Battle Bunker","yabnk.zip","1","1","0","0"
	,"Yuri Refinory","yurirfn.jpg","Yuri Refinory","yurrfn.zip","1","1","0","0"
	,"Yuri Service Depot","yadpot.JPG","Yuri Service Depot","yadepot.zip","1","1","0","0"
	,"Yuri Airpad","yapad.jpg","Yuri Airpad","yapad.zip","1","1","0","0"
	,"Yuri Tesla Coil","yatescoil.jpg","Yuri Tesla Coil (Not Finished)","yatescoil.zip","1","0","0","0"
	,"Yuri Tower","yatwr.jpg","Yuri Tower (Not Finished)","yatwr.zip","1","0","0","0"

	//Empire shps
	,"Empire Construction Yard","eacnyrd.jpg","Empire Construction Yard (Not Finished)(No Snow)","eacnyrd.zip","1","0","0","0"
	,"Empire Power Plant","eapwr.jpg","Empire Power Plant (Not Finished)(No Snow)","eapwr.zip","1","1","0","0"
	,"Empire Barracks","eabarx.jpg","Empire Barracks (Not Finished)(No Snow)","eabarx.zip","1","1","0","0"
	,"Empire Refinery","earfn.jpg","Empire Refinery (Not Finished)(No Snow)","earfn.zip","1","1","0","0"
	,"Empire Weapons Factory","eaweap.jpg","Empire Weapons Factory (Not Finished)(No Snow)","eaweap.zip","1","1","0","0"
	,"Empire Naval Yard","eayard.jpg","Empire Naval Yard (Not Finished)(No Snow)","eayard.zip","1","0","0","0"
	,"Empire Radar Dome","eardrdm.jpg","Empire Radar Dome (Not Finished)(No Snow)","eardrdm.zip","1","1","0","0"
	,"Empire Tech Building","eatch.jpg","Empire Tech Building (Not Finished)(No Snow)","eatch.zip","1","1","0","0"
	,"Empire Mecha Bay","eamchby.jpg","Empire Mecha Bay (Not Finished)(No Snow)","eamchby.zip","1","1","0","0"
	,"Empire Wall","eawall.jpg","Empire Wall (Not Finished)(No Snow)","eawall.zip","1","0","0","0"
	,"Empire Gun Emplacement","eagnpc.jpg","Empire Gun Emplacement (Not Finished)(No Snow)","eagnpc.zip","1","1","0","0"
	,"Empire Laser Gun","ealzrgn.jpg","Empire Laser Gun (Not Finished)(No Snow)","ealzrgn.zip","1","1","0","0"
	,"Empire AA Gun","eaagn.jpg","Empire AA Gun (Not Finished)(No Snow)","eaagn.zip","1","1","0","0"
	,"Empire Nano Swarm","eanano.jpg","Empire Nano Swarm (Not Finished)(No Snow)","eanano.zip","1","0","0","0"
	,"Empire Psychic Dominator","eapsydom.jpg","Empire Psychic Dominator (Not Finished)(No Snow)","eapsydom.zip","1","0","0","0"
	,"Concept Empire Barracks","NAEMBRX.jpg","Concept Empire Barracks (Not Finished)","NAEMBRX.zip","1","0","0","0"
	,"Yuriko Omega","yuriko.jpg","Yuriko Omega","yuriko.zip","1","0","0","0"
	,"Shinobi","ninja.jpg","Shinobi","ninja.zip","1","0","0","0"
	,"Rocket Angel","rctangl.jpg","Rocket Angel","rctangl.zip","1","0","0","0"
	,"Burst Drone","burdrn.jpg","Burst Drone","burdrn.zip","1","0","0","0"
	,"King Oni","eking.jpg","King Oni","eking.zip","1","0","0","0"
	,"Empire Side Bar","sidec04.jpg","Empire Side Bar","sidec04.zip","1","0","0","1"

	//Other shps
	,"Civilian Spy Dish","casptrdr.jpg","Civilian Spy Dish (Not Finished, no snow frames or buildup)","casptrdr.zip","1","0","0","0"
	,"Statue doodads pack 01","cgmoia.jpg","Statue doodads pack 01","cgmoia.zip","1","0","0","0"
	,"Statue doodads pack 02","cgothrst.jpg","Statue doodads pack 02","cgothrst.zip","1","0","0","0"
	,"Statue doodads pack 03","cgpeplst.jpg","Statue doodads pack 03","cgpeplst.zip","1","0","0","0"
	,"Statue doodads pack 04","cgtiki.jpg","Statue doodads pack 04","cgtiki.zip","1","0","0","0"
	,"Creature","striker.jpg","Some kind of creature (Not Finished)","striker.zip","1","0","0","0"
	,"Modern War Units ","modern.jpg","Collection of modern-ish war units","modern.zip","1","0","0","0"
	,"Orc Unit","orcinfy.jpg","Some kind of Orc unit (Not Finished)","orcinfy.zip","1","0","0","0"
	,"GDI Cannon","tscannon.jpg","Some kind of GDI Cannon (Not Finished/No Build-up) (no shape draw... needs TS pallet.)","tscannon.zip","1","0","0","1"
	,"GDI Infantry","gdiinfy.jpg","Some kind of GDI Infantry (Not Finished)","gdiinfy.zip","1","0","0","0"
	,"Nod Infantry","nodinfy.jpg","Some kind of Nod Infantry (Not Finished)","nodinfy.zip","1","0","0","0"
	,"Civilian Doodad Pack #1","oddpack01.jpg","A bunch of odd doodads","oddpack01.zip","1","0","0","0"
	,"Boot Camp Doodad Pack #1","bootcamppack.jpg","A Allied training camp doodad sprite pack (Not Finished)","bootcamppack.zip","1","0","0","0"
	,"Tables Doodad Pack #1","tablepack1.jpg","A pack of tables","tablepack1.zip","1","0","0","0"
	,"Vending Machine Doodad Pack #1","vendingpack.jpg","Vending Machine Doodad Pack 1","vendingpack.zip","1","0","0","0"
	,"Fair Ride Pack #1","fairpack1.jpg","Fair Ride Pack (Not Finished)","fairpack1.zip","1","0","0","0"
	,"Wild West Doodad Pack #1","westbitspack.jpg","Wild West Doodad Pack 1","westbitspack.zip","1","0","0","0"
	,"Wild West Building Pack #1","westbuildpack01.jpg","Wild West Building Pack 1","westbuildpack01.zip","1","0","0","0"
	,"Wild West Building Pack #2","westbuildpack02.jpg","Wild West Building Pack 2","westbuildpack02.zip","1","0","0","0"
	,"Wild West Building Pack #3","westbuildpack03.jpg","Wild West Building Pack 3","westbuildpack03.zip","1","0","0","0"
	,"Mario Kart sprites","mario.jpg","Collection of simple Mario Kart sprites.<br>Drivers are just eight frame rotations.<br>","mario.zip","1","0","0","0"
	,"Jump Jet Infantry","jumpjet.jpg","Jump Jet Infantry","jumpjet.zip","1","0","0","0"
	,"Civilian Ion Cannon","civion.jpg","Civilian Ion Cannon (Not Finished)","civion.zip","1","0","0","0"
	,"Civilian Nuke Silo","civnuke.jpg","Civilian Nuke Silo (Not Finished)","civnuke.zip","1","0","0","0"

	//Terrain
	,"Temperate Tree Set","tree.jpg","Temperate Tree Set","tree.zip","1","0","0","1"
	,"Lego Terrain Set","legotemp.jpg","Lego Terrain Set (Not Finished)","legotemp.zip","1","0","0","1"
	,"Space Terrain Set","space.jpg","Space Terrain Set (Not Finished)","space.zip","1","0","0","1"
	,"Floating Fortress Terrain Set","float.jpg","Floating Fortress Terrain Set (Not Finished)","float.zip","1","0","0","1"
	,"Fortress Terrain Set","fort.jpg","Fortress Terrain Set (Not Finished)","fort.zip","1","0","0","1"
	,"Temperate Terrain Set","temtermini.jpg","Temperate Terrain Set (Not Finished)","temter.zip","1","0","0","1"
	,"Ore Set","ore.jpg","Ore Set","ore.zip","1","0","0","1"
	,"Desert Terrain Set","destermini.jpg","Desert Terrain (Not Finished)","dester.zip","1","0","0","1"

	//Other
	,"Death","death.jpg","Longer decaying bodys","death.zip","1","0","0","0"
	,"Icon Backgrounds","icon.jpg","Edited Ra2/YR Backgrounds","icons.zip","0","0","0","1"
);

?>