<?php

$imageName=[
	['civipack.png','Civilian Vehicles - in a small city'],
	['emergency.png','Emergency vehicles in destroyed city'],
	['furyroad.png','A scene recreation of Mad Max Fury Road'],
	['mario.png','Mario Kart... What else needs to be said...'],
	['metroid.png','Samus Aran lands on planet Earth after receiving distress call...'],
	['race.png','A race track with race cars at the ready line'],
	['wild.png','A small wild west town'],
	['emp01.jpg','Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge'],
	['emp02.png','Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge'],
	['emp03.png','Failed mod that attempted to bring Empire of the rising sun into Yuris Revenge'],
	['russiabase.png','Failed mod that attempted to give each country its own set of unique buildings'],
	['alliedmech.png','Very pretty screenshot of allied stuff'],
	['ren2006.png','Two units converted from C&C Renegade'],
	['gdicannon2.PNG','A cannon I made years ago for C&C TS'],
	['TSPOWNS2006.PNG','A TS/FS screenshot of two new buildings for Nod'],
	['holdline.JPG','Screenshot of T-Day a failed mod called Tanyas revenge, this screenshot recreats d-day'],
	['civiwar2.jpg','A Failed civil war mod'],
	['civiwar02.PNG','A Failed civil war mod'],
	['civiwar03.PNG','A Failed civil war mod'],
	['id1.JPG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['id2.JPG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['ronten.JPG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['ronten3.JPG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['zorgon.gif','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['rollermech2.PNG','A high-ish polly render of a unit from Internal Destruction a Total Conversion for YR from 2005'],
	['attackgonebad.JPG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['hehe.JPG','Screenshot of my first mod idea that was to become Internal Destruction from 2004'],
	['wolfID2004.JPG','A early 3d render, inspired by TS wolverine from 2004'],
	['mad2003.png','A collection of my earliest graphics work from 2003'],
	['oneside.JPG','A collection of my earliest graphics work from 2003, all voxels made by hand in vxl edit'],
	['otherside.JPG','A collection of my earliest graphics work from 2003, all voxels made by hand in vxl edit'],
	['swat.png','Full S.W.A.T. deployment for terrorist at einstein\'s laboratory'],
	['train01.png','An old-ish time train passes through a facotry and suburban part of a city'],
	['train02.png','A factory part of town with convenient train docking'],
	['train03.png','A downtown Train Station with a few trains waiting to depart'],
	['sixhummers.png','Come on down to MadHQ\'s used car lot! All hummers 20% off!'],
	['jurassic.png','NA-NUH-NA-NA-NAH! Welcome to Jurassic Park!'],
	['arace.png','The fast and the furious Red Alert 2 style'],
	['rsfreedoom.png','Two Buildings I did for Robot Storm'],
	['nod.PNG','A Failed TS remake for Ra2/Yr'],
	['render.PNG','3d renders of buildings found on this site'],
	['renjunk.PNG','C&C Renegade buildings rendered for Ra2/YR'],
	['xmassmodfake.png','A Failed X-mas mod'],
	['monsters.gif','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['genfction.png','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['barx.gif','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['lzrgn.gif','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['plnt.gif','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['temp.PNG','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['uscnyd.gif','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['untitled_500.gif','A re-creation of Red Alert 3\'s Japan Hero Unit'],
	['modernwarz_560.png','A collection of concept work by me to see if I wanted to make a mod with it'],
	['gaion_212.gif','A un-used design for a allied ion cannon'],
	['sov_114.png','3 un-used soviet building designs'],
	['nanuke_164.gif','An un-used soviet nuke silo building design'],
	['yanuke_820.gif','An un-used yuri nuke silo building design'],
	['WIP1.png','An Conkers bad fur day concept'],
	['banner.gif','A banner to my old Ra2 Madness site'],
	['build.PNG','Some concept I did for a mod I was trying to create, called \'Mechanical Eradication\' (2010)'],
	['civibuildings.PNG','A bunch of civi buildings'],
	['DOW.PNG','An attempt to make a Dawn of war mod (failed)'],
	['fakeasiawip.png','A first pass at an empire of the rising sun faction'],
	['FLNUKE3.gif','A building I did for Robot Storm'],
	['floatioingisland4.PNG','A small floating island style map'],
	['FLTECHANMTST.gif','A building I did for Robot Storm'],
	['indexbanner.gif','A banner for my very first mod Internal Destruction\'s web site'],
	['JUGGWIP.gif','A unit for a lego mod I was once working on (failed)'],
	['jugrender.PNG','A unit for a lego mod I was once working on (failed)'],
	['LEGOTERRAIN.PNG','Terrain for a lego mod I was once working on (failed)'],
	['LEGOTERRAIN2.PNG','Terrain for a lego mod I was once working on (failed)'],
	['lol2.PNG','Space terrain made for fun.'],
	['Middleearth.PNG','A collection of concept work by me to see if I wanted to make a mod with it'],
	['oie_ReKdY0ub4B4z.gif','A bunch of spinning logos for a mod called Robot Storm'],
	['preview.PNG','A collection of concept work by me to see if I wanted to make a mod with it'],
	['RA_ALLIES.PNG','A collection of concept work by me to see if I wanted to make a mod with it'],
	['ra2madness2008_01.PNG','A screenshot of RA2 Madness'],
	['ra2madness2008_03.PNG','A screenshot of RA2 Madness'],
	['TERAINSTUFF.PNG','Renders of terrain'],
	['wh40k.PNG','Renders of terrain for a DOW theme'],
	['yrbuild.PNG','A few unfinished Ra2 buildings'],
	['weirdbarx.PNG','A Joke building I made for my mod Ra2 madness'],
	['ra2gen.PNG','USA and GLA buildings rendered for Ra2 (failed)'],
	['screen01.PNG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['screen02.PNG','Screenshot of my very first mod Internal Destruction a Total Conversion for YR from 2005'],
	['tanyapromo.JPG','Screenshot of T-Day a failed mod called Tanyas revenge'],
	['tanyapromo1.gif','Screenshot of T-Day a failed mod called Tanyas revenge'],
	['tanyapromo2.gif','Screenshot of T-Day a failed mod called Tanyas revenge'],
	['TSMECHASST.PNG','Screenshot of some kind of odd TS-mech mod']
];

?>