<?php

$vxl=array(
	//Allied vxl
	//Aircraft
	"Aircraft","crftpln.jpg","Aircraft","crftcrpln.zip","1","1","0","Allied","Aerial"
	,"Firefly","firfly.jpg","Firefly","firefly.zip","1","1","0","Allied","Aerial"
	,"Dragonfly","drgnfly.jpg","Dragonfly","drngfly.zip","1","1","0","Allied","Aerial"
	,"RA3's Harbinger Gunship","hinbrige.jpg","RA3's Harbinger Gunship","hndbrd.zip","1","1","0","Allied","Aerial"
	,"RA3's Vindicator","vindi.jpg","RA3's Vindicator","vindi.zip","1","1","0","Allied","Aerial"
	,"RA3's Apollo","apollo.jpg","RA3's Apollo","apollo.zip","1","1","0","Allied","Aerial"
	,"RA3's Cryocopter","CRYOCHOP.jpg","RA3's Cryocopter","cryochp.zip","1","1","0","Allied","Aerial"
	,"ATLS","atls.jpg","ATLS","atls.zip","1","0","0","Allied","Aerial"
	,"Bomber","bumerbomb.JPG","Bomber","fortress.zip","1","0","0","Allied","Aerial"
	,"Hunter Killer","hntkll.jpg","Hunter Killer","hntkll.zip","1","0","0","Allied","Aerial"
	,"Commache","comch.jpg","Commache","comch.zip","1","0","0","Allied","Aerial"
	,"Station","staton.jpg","Station","staton.zip","1","0","0","Allied","Aerial"
	,"Allied Bomber","prebmbr.jpg","Allied Bomber","prebmbr.zip","1","0","0","Allied","Aerial"
	,"Allied Fighter","alifig.jpg","Allied Fighter","alifig.zip","1","0","0","Allied","Aerial"
	,"Allied Archangel","alihovshp.jpg","Allied Archangel-class from Gundam Seed","alihovshp.zip","1","0","0","Allied","Aerial"
	,"Allied Craft","alicrftfly.jpg","Allied Craft","alicrftfly.zip","1","0","0","Allied","Aerial"

	//Ground
	,"M1A1 Abrams Tank","m1a1.JPG","The vxl I submitted to the first Voxel Competition ever, in March/April 2004, And got 3rd out of 3.<br>Entrants were, in order of place: 1st)MigEater, 2nd)raminator, 3rd)MadHQ M1A1 Abrams Tank","m1a1.zip","1","0","0","Allied","Ground"
	,"RA3's Riptide ACV","riptid.jpg","RA3's Riptide ACV","riptid.zip","1","1","0","Allied","Ground"
	,"RA3's Future Tank X-1","futrtnk.jpg","RA3's Future Tank X-1","futtnkx1.zip","1","1","0","Allied","Ground"
	,"APC","apc.jpg","APC","apc.zip","1","1","0","Allied","Ground"
	,"Small Mech","stryker.JPG","Small Mech","asmmhk.zip","1","1","0","Allied","Ground"
	,"Chrono Prism","chropris.JPG","Chrono Prism","chroprim.zip","1","1","0","Allied","Ground"
	,"Zuse Tank","zusetnk.jpg","Zuse Tank","zusetnk.zip","1","1","0","Allied","Ground"
	,"Plasma Tank","shadow.jpg","Plasma Tank","aplstnk.zip","1","1","0","Allied","Ground"
	,"Plasma Tank","aplsmtnk.jpg","Plasma Tank","aplsmtnk.zip","1","0","0","Allied","Ground"
	,"Sonic Tank","sonictnk.jpg","Sonic Tank","sonictnk.zip","1","0","0","Allied","Ground"
	,"Odyssey","odsy.JPG","Odyssey (Based on ED-209 From Robocop)","odymhk.zip","1","1","0","Allied","Ground"
	,"Chrono Missile Tank","chromis.JPG","Chrono Missile Tank","chromisl.zip","1","1","0","Allied","Ground"
	,"Hovercraft","hover.JPG","Hovercraft (Tjframes design for a hovercraft)","hover.zip","1","1","0","Allied","Ground"
	,"Phantom Tank","phntnk.jpg","Phantom Tank","phntnk.zip","1","0","0","Allied","Ground"
	,"Mech","tallon.jpg","Mech","tallon.zip","1","0","0","Allied","Ground"
	,"Mirage Tank","miragtnk.jpg","Mirage Tank","miragtnk.zip","1","0","0","Allied","Ground"
	,"Rocket Buggy","frog.jpg","Rocket Buggy","frog.zip","1","0","0","Allied","Ground"
	,"Predator Tank","pred.jpg","Predator Tank","pred.zip","1","0","0","Allied","Ground"
	,"APC","rapc.jpg","APC","rapc.zip","1","0","0","Allied","Ground"
	,"Wolverine","wlfrin.jpg","Wolverine","wlfrin.zip","1","0","0","Allied","Ground"
	,"Titan","titan.jpg","Titan","titan.zip","1","0","0","Allied","Ground"
	,"Juggernaut","jugg.jpg","Juggernaut","jugg.zip","1","0","0","Allied","Ground"
	,"Weather Tank","wetnk.jpg","Weather Tank","wetnk.zip","1","0","0","Allied","Ground"
	,"Tank","ptnk.jpg","Tank","ptnk.zip","1","0","0","Allied","Ground"
	,"Epic Tank","mrgtnk.jpg","Epic Tank","mrgtnk.zip","1","0","0","Allied","Ground"
	,"Aircraft Truck","crftcr.jpg","Aircraft Truck","crftcr.zip","1","0","0","Allied","Ground"
	,"Buggy","bug.jpg","Buggy","bug.zip","1","0","0","Allied","Ground"
	,"Artillery Mecha","artymch.jpg","Artillery Mecha","artmch.zip","1","0","0","Allied","Ground"
	,"C&C3 Predator Tank","cnc3pred.jpg","C&C3 Predator Tank","cnc3pred.zip","1","0","0","Allied","Ground"
	,"Mirage Battle Fortress","mbf.jpg","Mirage Battle Fortress","mbf.zip","1","0","0","Allied","Ground"
	,"Hover Tank","stnk.jpg","Hover Tank","stnk.zip","1","0","0","Allied","Ground"
	,"Allied APC","apctw.jpg","Allied APC","apctw.zip","1","0","0","Allied","Ground"
	,"Allied Tank","aqtnk.jpg","Allied Tank","aqtnk.zip","1","0","0","Allied","Ground"
	,"Allied Mammoth Tank","mammy.jpg","Allied Mammoth Tank","mammytw.zip","1","0","0","Allied","Ground"
	,"Allied Hover Scout","utnk.jpg","Allied Hover Scout","utnk.zip","1","0","0","Allied","Ground"

	//Navy
	,"Aircraft Carrier","carrier.JPG","The vxl I subbemited to the April 2004 CNCG Voxel Competition, And got 1st place<br>Aircraft Carrier","carrier.zip","1","0","0","Allied","Naval"
	,"RA3's Assault Destroyer","dest.jpg","RA3's Assault Destroyer","adestry.zip","1","1","0","Allied","Naval"
	,"RA3's Hydrofoil","hydrofoil.jpg","RA3's Hydrofoil","hydro.zip","1","1","0","Allied","Naval"
	,"Chrono Freight","chroshp.JPG","Chrono Freight","chroshp.zip","1","0","0","Allied","Naval"
	,"Missle Ship","amislshp.JPG","Missle Ship","sharkship.zip","1","0","0","Allied","Naval"
	,"Helicarrier","hlicar.JPG","Helicarrier","helicar.zip","1","0","0","Allied","Naval"
	,"Allied stringray sub","allisubsti.jpg","Allied stringray sub","allisubsti.zip","1","0","0","Allied","Naval"
	,"Missle Sub","missub.jpg","Missle Sub","missub.zip","1","0","0","Allied","Naval"
	,"Allied Ekranoplan","alidbomb.jpg","Allied Caspian Sea Monster Ekranoplan","alidbomb.zip","1","0","0","Allied","Naval"

	//Soviet vxl
	//Aircraft
	,"Aircraft","drgn.jpg","Aircraft","drgn.zip","1","1","0","Soviet","Aerial"
	,"Aircraft","jager.jpg","Aircraft","jager.zip","1","1","0","Soviet","Aerial"
	,"Aircraft","bomber.jpg","Aircraft","bmber.zip","1","1","0","Soviet","Aerial"
	,"Aircraft","mosqto.jpg","Aircraft","mosqto.zip","1","1","0","Soviet","Aerial"
	,"Kirov Gunship","gnzep.jpg","Kirov Gunship","gnzep.zip","1","1","0","Soviet","Aerial"
	,"RA3's Mig","mig.jpg","RA3's Mig","smig.zip","1","1","0","Soviet","air"
	,"RA3's Twinblade","twinblade.jpg","RA3's Twinblade","twnbld.zip","1","1","0","Soviet","Aerial"
	,"Attack Chopper","atkchp.jpg","Attack Chopper","atkchp.zip","1","1","0","Soviet","Aerial"
	,"M-15 Faggot","m15fagot.jpg","M-15 Faggot","m15fagot.zip","1","0","0","Soviet","Aerial"
	,"P-51","p51.jpg","P-51","p51.zip","1","0","0","Soviet","Aerial"
	,"RA3's Mig","mig.jpg","RA3's Mig","mig.zip","1","0","0","Soviet","Aerial"
	,"Soviet Ship","sovshpfly.jpg","Soviet Ship","sovshpfly.zip","1","0","0","Soviet","Aerial"
	,"Soviet Salamis","sovshphovcrft.jpg","Soviet Salamis-class starship","sovshphovcrft.zip","1","0","0","Soviet","Aerial"

	//Ground
	,"RA3's Sickle","sickle.jpg","The vxl I submitted to the TFOtbBPVCpbBaTMtnC VoxelComp May/June' 2008, And got 2nd place<br>RA3's Sickle","sickle.zip","1","1","0","Soviet","Ground"
	,"Bull Dog Mech","blmch.jpg","The vxl I submitted to the VoxelComp Dec. '06, And got 1st place<br>Bull Dog Mech","bulldog.zip","1","1","0","Soviet","Ground"
	,"Centurion Siege Crawler","cen.jpg","The vxl I submitted to the October 2004 CNCG Voxel Competition, And got 1st place<br>Centurion Siege Crawler","cen.zip","1","1","0","Soviet","Ground"
	,"Mech","smchspr.jpg","Mech","smchsp.zip","1","1","0","Soviet","Ground"
	,"RA3's Grinder","grinder.jpg","RA3's Grinder","grndtnk.zip","1","1","0","Soviet","Ground"
	,"Uranium Tank","urmtnk.jpg","Uranium Tank","urmtnk.zip","1","1","0","Soviet","Ground"
	,"Flame Tank","fltnk.JPG","Flame Tank","fltnk.zip","1","1","0","Soviet","Ground"
	,"Stealth Tank","stlhtnk.JPG","Stealth Tank","stlhtnk.zip","1","1","0","Soviet","Ground"
	,"Drone Launcher","drnlnch.jpg","Drone Launcher","drnlnchr.zip","1","1","0","Soviet","Ground"
	,"Missle Bike","misbik.jpg","Missle Bike","misbik.zip","1","1","0","Soviet","Ground"
	,"Missle Track","mstrk.jpg","Flame Tank","mistrk.zip","1","0","0","Soviet","Ground"
	,"Tesla Tank","ttnk.jpg","Tesla Tank (Tjframes design for a Tesla Tank)","ttnk.zip","1","0","0","Soviet","Ground"
	,"Iron Curtain Tank","irontnk.jpg","Iron Curtain Tank","irontnk.zip","1","0","0","Soviet","Ground"
	,"Half-Track","halftrak.jpg","Half-Track","hlftrck.zip","1","0","0","Soviet","Ground"
	,"Seismic Tank","seis.JPG","Seismic Tank","sizmtnk.zip","1","0","0","Soviet","Ground"
	,"Tank Killer","tnkkill.JPG","Tank Killer","tnkkill.zip","1","1","0","Soviet","Ground"
	,"Pitbull","pitbull.JPG","Pitbull","pitbll.zip","1","1","0","Soviet","Ground"
	,"Nuke Cannon","nukcn.jpg","Nuke Cannon","nukcn.zip","1","0","0","Soviet","Ground"
	,"Rocket Buggy","rctbugy.jpg","Rocket Buggy","rctbugy.zip","1","0","0","Soviet","Ground"
	,"Artillery","svaty.jpg","Artillery","svaty.zip","1","0","0","Soviet","Ground"
	,"Apocalypse Tank","apoz.jpg","Apocalypse Tank","apoz.zip","1","0","0","Soviet","Ground"
	,"Nuke Tank","nuktank.jpg","Nuke Tank","nuktank.zip","1","0","0","Soviet","Ground"
	,"Tank Killer","sotnkkller.jpg","Tank Killer","sotnkkller.zip","1","0","0","Soviet","Ground"
	,"Rhino Tank","rinotnk.jpg","Rhino Tank","rinotnk.zip","1","0","0","Soviet","Ground"
	,"Battle Tank","satnk.jpg","Battle Tank","satnk.zip","1","0","0","Soviet","Ground"
	,"Hover Sky Sweeper","hvraa.jpg","Hover Sky Sweeper","hvraa.zip","1","0","0","Soviet","Ground"
	,"Assault Tesla Tank","tvtnk.jpg","Assault Tesla Tank","tvtnk.zip","1","0","0","Soviet","Ground"
	,"Repair Drone","rpedrn.jpg","Repair Drone","repdrn.zip","1","0","0","Soviet","Ground"
	,"Epic Tank","epic.jpg","Epic Tank","epic.zip","1","0","0","Soviet","Ground"
	,"Radiation Tank","radtnk.jpg","Radiation Tank","radtnk.zip","1","0","0","Soviet","Ground"
	,"Aircraft Truck","airtrk.jpg","Aircraft Truck","airtrk.zip","1","0","0","Soviet","Ground"
	,"Missle Tank","smisltnk.jpg","Missle Tank","smisltnk.zip","1","0","0","Soviet","Ground"
	,"Beaver Scud","bevscud.jpg","Beaver Scud","bevscud.zip","1","0","0","Soviet","Ground"
	,"Soviet Vessel","sovvess.jpg","Soviet Vessel","sovvess.zip","1","1","0","Soviet","Ground"

	//Navy
	,"Flak Boat","hypr.jpg","Flak Boat","hypr.zip","1","1","0","Soviet","Naval"
	,"Missle Ship","sovmisship.jpg","Missle Ship","sovmisshiptur.zip","1","0","0","Soviet","Naval"
	,"Soviet Submarine","sovsubm.jpg","Soviet Submarine","sovsubm.zip","1","0","0","Soviet","Naval"
	,"Soviet Stringray Sub","sovsubsti.jpg","Soviet Stringray Sub","sovsubsti.zip","1","0","0","Soviet","Naval"
	,"Soviet Submarine","sovwidsub.jpg","Soviet Submarine","sovwidsub.zip","1","0","0","Soviet","Naval"

	//Yuri vxl
	//Aircraft
	,"Aircraft","upln.jpg","Aircraft","upln.zip","1","1","0","Yuri","Aerial"
	,"Mind Disk","minddisk.jpg","Aircraft","minddisk.zip","1","0","0","Yuri","Aerial"
	,"Light Disk","diskatk.jpg","Aircraft","diskatk.zip","1","0","0","Yuri","Aerial"
	,"Chaos Bomber","causbmbr.jpg","Aircraft","causbmbr.zip","1","0","0","Yuri","Aerial"
	,"Face","yaface.jpg","Face","yaface.zip","1","0","0","Yuri","Aerial"

	//Ground
	,"Puppeteer","mindhand.jpg","This was a request from Atomic_Noodles, I never got around finishing it...<br>But I might as well release it.","mindhand.zip","1","0","0","Yuri","Ground"
	,"Face Blaster","yafaceblaster.jpg","The vxl I submitted to CnC Guild Voxel Comp 09. Shockingly I took first place<br>Face Blaster","faceblaster.zip","1","0","0","Yuri","Ground"
	,"Hover Trike","etnk.jpg","Hover Trike","etnk.zip","1","1","0","Yuri","Ground"
	,"Tumbler","tumbl.jpg","Tumbler","tumbl.zip","1","1","0","Yuri","Ground"
	,"Kinetic Tank","kntnk.jpg","Kinetic Tank","kntnk.zip","1","1","0","Yuri","Ground"
	,"Genetic Mutator Vehical","gntnk.jpg","Genetic Mutator Vehical","gntnk.zip","1","1","0","Yuri","Ground"
	,"Shadow Tank","shdtnk.jpg","Shadow Tank","shdtnk.zip","1","1","0","Yuri","Ground"
	,"Plasma Tank","plsmtnk.jpg","Plasma Tank","yaplstnk.zip","1","1","0","Yuri","Ground"
	,"Advanced Tank","yaadvtnk.jpg","Advanced Tank","yadvtnk.zip","1","0","0","Yuri","Ground"
	,"Mech","stngr.jpg","Mech","stngr.zip","1","0","0","Yuri","Ground"
	,"Hunter Killer","htkltnk.jpg","Hunter Killer","htkltnk.zip","1","0","0","Yuri","Ground"
	,"IG-227 Hailfire-Class Droid Tank","hlfrdrd.jpg","IG-227 Hailfire-Class Droid Tank","hlfrdrd.zip","1","0","0","Yuri","Ground"
	,"Droid Tank","catnkdrn.jpg","Droid Tank","catnkdrn.zip","1","0","0","Yuri","Ground"
	,"Mecha","yamech.jpg","Mecha","yamech.zip","1","0","0","Yuri","Ground"
	,"Epic Tank","huntkill.jpg","Epic Tank","huntkill.zip","1","0","0","Yuri","Ground"
	,"Aircraft Truck","yahvcr.jpg","Aircraft Truck","yahcr.zip","1","0","0","Yuri","Ground"
	,"Plasma Tank","yaplsat.jpg","Plasma Tank","yaplsm.zip","1","0","0","Yuri","Ground"
	,"Trike","sptrk.jpg","Trike","sptrk.zip","1","0","0","Yuri","Ground"
	,"Corkscrew","corkscrew.jpg","Corkscrew","corkscrew.zip","1","0","0","Yuri","Ground"
	,"Mobile Construction Vehicle","pcv.jpg","Mobile Construction Vehicle","pcv.zip","1","0","0","Yuri","Ground"
	,"Tank","qtnk.jpg","Tank","qtnk.zip","1","0","0","Yuri","Ground"

	//Navy
	,"Aircraft Carrier","yacarri.jpg","Aircraft Carrier","yacarri.zip","1","1","0","Yuri","Naval"
	,"Gatling Boat","yagatboat.jpg","Gatling Boat","gatboat.zip","1","1","0","Yuri","Naval"
	,"Mind Control Ship","mindship.jpg","Mind Control Ship","mindship.zip","1","1","0","Yuri","Naval"

	//Civilian vxl
	//Aircraft
	,"Propeller Plane","fcciv09.jpg","Propeller Plane","fcciv09.zip","1","0","0","Civilian","Aerial"
	,"Propeller Plane","fcciv11.jpg","Propeller Plane","fcciv11.zip","1","0","0","Civilian","Aerial"
	,"Propeller Plane","fcciv14.jpg","Propeller Plane","fcciv14.zip","1","0","0","Civilian","Aerial"
	,"Propeller Plane","propplan1.jpg","Propeller Plane","propplan1.zip","1","0","0","Civilian","Aerial"
	,"Propeller Plane","propplan2.jpg","Propeller Plane","propplan2.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","fcciv06.jpg","Passenger Plane","fcciv06.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","fcciv08.jpg","Passenger Plane","fcciv08.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","fcciv10.jpg","Passenger Plane","fcciv10.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","passpln1.jpg","Passenger Plane","passpln1.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","passpln2.jpg","Passenger Plane","passpln2.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","passpln3.jpg","Passenger Plane","passpln3.zip","1","0","0","Civilian","Aerial"
	,"Passenger Plane","passpln4.jpg","Passenger Plane","passpln4.zip","1","0","0","Civilian","Aerial"
	,"Space Shuttle","spashut1.jpg","Space Shuttle","spashut1.zip","1","0","0","Civilian","Aerial"
	,"Space Shuttle","spashut2.jpg","Space Shuttle","spashut2.zip","1","0","0","Civilian","Aerial"
	,"Blimp","airblimps.jpg","Blimp","airblimps.zip","1","0","0","Other","Aerial"

	//Ground
	,"Hover Craft","fcciv07.jpg","Hover Craft","fcciv07.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport01.jpg","Sport Car","sport01.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport02.jpg","Sport Car","sport02.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport03.jpg","Sport Car","sport03.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport04.jpg","Sport Car","sport04.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport05.jpg","Sport Car","sport05.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport06.jpg","Sport Car","sport06.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport07.jpg","Sport Car","sport07.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport08.jpg","Sport Car","sport08.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport09.jpg","Sport Car","sport09.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport10.jpg","Sport Car","sport10.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport11.jpg","Sport Car","sport11.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport12.jpg","Sport Car","sport12.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport13.jpg","Sport Car","sport13.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport14.jpg","Sport Car","sport14.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport15.jpg","Sport Car","sport15.zip","1","0","0","Civilian","Ground"
	,"Sport Car","sport16.jpg","Sport Car","sport16.zip","1","0","0","Civilian","Ground"
	,"Beetle","civybeetle.jpg","Beetle","civybeetle.zip","1","0","0","Civilian","Ground"
	,"Buggy","civybuggy9.jpg","Buggy","civybuggy9.zip","1","0","0","Civilian","Ground"
	,"Buick","civybuick.jpg","Buick","civybuick.zip","1","0","0","Civilian","Ground"
	,"Buick","civybuick2.jpg","Buick","civybuick2.zip","1","0","0","Civilian","Ground"
	,"Cadillac","civycadillac.jpg","Cadillac","civycadillac.zip","1","0","0","Civilian","Ground"
	,"Coupe","civycoupe.jpg","Coupe","civycoupe.zip","1","0","0","Civilian","Ground"
	,"Coupe","civycoupe1932.jpg","Coupe","civycoupe1932.zip","1","0","0","Civilian","Ground"
	,"EH Wagon","civyehwagon.jpg","EH Wagon","civyehwagon.zip","1","0","0","Civilian","Ground"
	,"Mercedes","civymercades.jpg","Mercedes","civymercades.zip","1","0","0","Civilian","Ground"
	,"Plymouth","civyplymouth2.jpg","Plymouth","civyplymouth2.zip","1","0","0","Civilian","Ground"
	,"Valiant","civyvaliant.jpg","Valiant","civyvaliant.zip","1","0","0","Civilian","Ground"
	,"Hotrod","civyhotrod.jpg","Hotrod","civyhotrod.zip","1","0","0","Civilian","Ground"
	,"Sci-fi Car","civascificar1.jpg","Sci-fi Car","civascificar1.zip","1","0","0","Civilian","Ground"
	,"Sci-fi Car","civascificar2.jpg","Sci-fi Car","civascificar2.zip","1","0","0","Civilian","Ground"
	,"Sci-fi Car","civascificar3.jpg","Sci-fi Car","civascificar3.zip","1","0","0","Civilian","Ground"
	,"Monster Car","VEHICL.jpg","Monster Car","VEHICL.zip","1","0","0","Civilian","Ground"
	,"Future Car","VEHICTR.jpg","Future Car","VEHICTR.zip","1","0","0","Civilian","Ground"
	,"Muscle Car","VEHICY.jpg","Muscle Car","VEHICY.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace1.jpg","Race Car","civirace1.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace2.jpg","Race Car","civirace2.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace3.jpg","Race Car","civirace3.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace4.jpg","Race Car","civirace4.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace5.jpg","Race Car","civirace5.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace6.jpg","Race Car","civirace6.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace7.jpg","Race Car","civirace7.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace8.jpg","Race Car","civirace8.zip","1","0","0","Civilian","Ground"
	,"Race Car","civirace9.jpg","Race Car","civirace9.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr01.jpg","Hover Car","scihovr01.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr02.jpg","Hover Car","scihovr02.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr03.jpg","Hover Car","scihovr03.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr04.jpg","Hover Car","scihovr04.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr05.jpg","Hover Car","scihovr05.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr07.jpg","Hover Car","scihovr07.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr08.jpg","Hover Car","scihovr08.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr09.jpg","Hover Car","scihovr09.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr12.jpg","Hover Car","scihovr12.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr18.jpg","Hover Car","scihovr18.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr27.jpg","Hover Car","scihovr27.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr28.jpg","Hover Car","scihovr28.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr29.jpg","Hover Car","scihovr29.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr22.jpg","Hover Car","scihovr22.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr30.jpg","Hover Car","scihovr30.zip","1","0","0","Civilian","Ground"
	,"Hover Car","scihovr06.jpg","Hover Car","scihovr06.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck01.jpg","Pickup Truck","civytruck01.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck02.jpg","Pickup Truck","civytruck02.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck03.jpg","Pickup Truck","civytruck03.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck04.jpg","Pickup Truck","civytruck04.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck05.jpg","Pickup Truck","civytruck05.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck06.jpg","Pickup Truck","civytruck06.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck07.jpg","Pickup Truck","civytruck07.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck08.jpg","Pickup Truck","civytruck08.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck09.jpg","Pickup Truck","civytruck09.zip","1","0","0","Civilian","Ground"
	,"Pickup Truck","civytruck10.jpg","Pickup Truck","civytruck10.zip","1","0","0","Civilian","Ground"
	,"Camper Truck","civacamptrck.jpg","Camper Truck","civacamptrck.zip","1","0","0","Civilian","Ground"
	,"Holden Truck","civyholden.jpg","Holden Truck","civyholden.zip","1","0","0","Civilian","Ground"
	,"Holden UTE","civyholdenute.jpg","Holden UTE","civyholdenute.zip","1","0","0","Civilian","Ground"
	,"Dodge Truck","civydodgetruck.jpg","Dodge Truck","civydodgetruck.zip","1","0","0","Civilian","Ground"
	,"Tow Truck","VEHICK.jpg","Tow Truck","VEHICK.zip","1","0","0","Civilian","Ground"
	,"Red Van","minivan00.jpg","Red Van","minivan00.zip","1","0","0","Civilian","Ground"
	,"Silver Minivan","minivan01.jpg","Silver Minivan","minivan01.zip","1","0","0","Civilian","Ground"
	,"Red Minivan","minivan02.jpg","Red Minivan","minivan02.zip","1","0","0","Civilian","Ground"
	,"Tan Minivan","minivan03.jpg","Tan Minivan","minivan03.zip","1","0","0","Civilian","Ground"
	,"Copper Minivan","minivan04.jpg","Copper Minivan","minivan04.zip","1","0","0","Civilian","Ground"
	,"Blue Van","minivan05.jpg","Blue Van","minivan05.zip","1","0","0","Civilian","Ground"
	,"White Van","minivan06.jpg","White Van","minivan06.zip","1","0","0","Civilian","Ground"
	,"Green Minivan","minivan07.jpg","Green Minivan","minivan07.zip","1","0","0","Civilian","Ground"
	,"Black Minivan","minivan08.jpg","Black Minivan","minivan08.zip","1","0","0","Civilian","Ground"
	,"Volkswagen Van","minivan09.jpg","Volkswagen Van","minivan09.zip","1","0","0","Civilian","Ground"
	,"Blue Van","civavan.jpg","Blue Van","civavan.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer1.jpg","Hummer","hummer1.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer2.jpg","Hummer","hummer2.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer3.jpg","Hummer","hummer3.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer4.jpg","Hummer","hummer4.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer5.jpg","Hummer","hummer5.zip","1","0","0","Civilian","Ground"
	,"Hummer","hummer6.jpg","Hummer","hummer6.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster1.jpg","Monster Truck","monster1.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster2.jpg","Monster Truck","monster2.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster3.jpg","Monster Truck","monster3.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster4.jpg","Monster Truck","monster4.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster5.jpg","Monster Truck","monster5.zip","1","0","0","Civilian","Ground"
	,"Monster Truck","monster6.jpg","Monster Truck","monster6.zip","1","0","0","Civilian","Ground"
	,"Mack Truck","civymack.jpg","Mack Truck","civymack.zip","1","0","0","Civilian","Ground"
	,"Recreational vehicle","civarv.jpg","Recreational vehicle","civarv.zip","1","0","0","Civilian","Ground"
	,"Moving Truck","inttruck.jpg","Moving Truck","inttruck.zip","1","0","0","Civilian","Ground"
	,"Money Truck","moneyusvan.jpg","Money Truck","moneyusvan.zip","1","0","0","Civilian","Ground"
	,"Money Van","moneyvan.jpg","Money Van","moneyvan.zip","1","0","0","Civilian","Ground"
	,"YOU-Haul","uhaul01.jpg","YOU-Haul","uhaul01.zip","1","0","0","Civilian","Ground"
	,"YOU-Haul","uhaul02.jpg","YOU-Haul","uhaul02.zip","1","0","0","Civilian","Ground"
	,"Street Sweeper","wrksmlsweep.jpg","Street Sweeper","wrksmlsweep.zip","1","0","0","Civilian","Ground"
	,"Street Sweeper","wrksweeper.jpg","Street Sweeper","wrksweeper.zip","1","0","0","Civilian","Ground"
	,"Ice Cream Truck","icecream.jpg","Ice Cream Truck","icecream.zip","1","0","0","Civilian","Ground"
	,"Recycle Truck","recycle.jpg","Recycle Truck","recycle.zip","1","0","0","Civilian","Ground"
	,"Red Tour Bus","redbus.jpg","Red Tour Bus","redbus.zip","1","0","0","Civilian","Ground"
	,"UPS Vehicle","ups.jpg","UPS Vehicle","ups.zip","1","0","0","Civilian","Ground"
	,"USPS Truck","usps.jpg","USPS Truck","usps.zip","1","0","0","Civilian","Ground"
	,"Truck Stair","workcar03.jpg","Truck Mounted Passenger Stair","workcar03.zip","1","0","0","Civilian","Ground"
	,"Pushback Tug","workcar02.jpg","Pushback Tug","workcar02.zip","1","0","0","Civilian","Ground"
	,"Pushback Tug","workcar04.jpg","Pushback Tug","workcar04.zip","1","0","0","Civilian","Ground"
	,"Pushback Tug","workcar06.jpg","Pushback Tug","workcar06.zip","1","0","0","Civilian","Ground"
	,"Medical Van","medvan.jpg","Medical Van","medvan.zip","1","0","0","Civilian","Ground"
	,"Fire Truck","fcciv02.jpg","Fire Truck","fcciv02.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civyemc00.jpg","Emergency Response Vehicle","civyemc00.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Truck","civyemc01.jpg","Emergency Response Truck","civyemc01.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civyemc02.jpg","Emergency Response Vehicle","civyemc02.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Truck","civyemc03.jpg","Emergency Response Truck","civyemc03.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civyemc04.jpg","Emergency Response Vehicle","civyemc04.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civyemc05.jpg","Emergency Response Vehicle","civyemc05.zip","1","0","0","Civilian","Ground"
	,"Emergency Ambulance","civyemc06.jpg","Emergency Ambulance","civyemc06.zip","1","0","0","Civilian","Ground"
	,"Fire Truck","civyemc07.jpg","Fire Truck","civyemc07.zip","1","0","0","Civilian","Ground"
	,"Flatbed Tow Truck","civyemc08.jpg","Flatbed Tow Truck","civyemc08.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civaemcy01.jpg","Emergency Response Vehicle","civaemcy01.zip","1","0","0","Civilian","Ground"
	,"Emergency Response Vehicle","civaemcy02.jpg","Emergency Response Vehicle","civaemcy02.zip","1","0","0","Civilian","Ground"
	,"Armored Troop Carrier","VEHICN.jpg","Armored Troop Carrier","VEHICN.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT1.jpg","S.W.A.T Voxel","SWAT1.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT2.jpg","S.W.A.T Voxel","SWAT2.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT3.jpg","S.W.A.T Voxel","SWAT3.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT4.jpg","S.W.A.T Voxel","SWAT4.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT5.jpg","S.W.A.T Voxel","SWAT5.zip","1","0","0","Civilian","Ground"
	,"S.W.A.T Voxel","SWAT6.jpg","S.W.A.T Voxel","SWAT6.zip","1","0","0","Civilian","Ground"
	,"Gas Semi-truck","civygas1.jpg","Gas Semi-truck","civygas1.zip","1","0","0","Civilian","Ground"
	,"Gas Semi-truck","civygas2.jpg","Gas Semi-truck","civygas2.zip","1","0","0","Civilian","Ground"
	,"MAN Truck","civyman.jpg","MAN Truck","civyman.zip","1","0","0","Civilian","Ground"
	,"Cargo Truck","civycargo.jpg","Cargo Truck","civycargo.zip","1","0","0","Civilian","Ground"
	,"Vozidla","civyvozidla.jpg","Vozidla","civyvozidla.zip","1","0","0","Civilian","Ground"
	,"Farm Tractor","civytrctr6.jpg","Farm Tractor","civytrctr6.zip","1","0","0","Civilian","Ground"
	,"Combine Harvester","civytrctr7.jpg","Combine Harvester","civytrctr7.zip","1","0","0","Civilian","Ground"
	,"Putt-Putt Tractor","vhefarm2.jpg","Putt-Putt Tractor","vhefarm2.zip","1","0","0","Civilian","Ground"
	,"Utility Tractor","vhefarm5.jpg","Utility Tractor","vhefarm5.zip","1","0","0","Civilian","Ground"
	,"Combine","vhefarm6.jpg","Combine","vhefarm6.zip","1","0","0","Civilian","Ground"
	,"Combine","trctr4.jpg","Combine","trctr4.zip","1","0","0","Civilian","Ground"
	,"Snow Vehicle","fcciv03.jpg","Snow Vehicle","fcciv03.zip","1","0","0","Civilian","Ground"
	,"Snow Vehicle","fcciv05.jpg","Snow Vehicle","fcciv05.zip","1","0","0","Civilian","Ground"
	,"Snow Plow Truck","snowtruck01.jpg","A Civi Vehicles voxel pack","snowtruck01.zip","1","0","0","Civilian","Ground"
	,"Snow Groomer","snowtruck02.jpg","Snow Groomer","snowtruck02.zip","1","0","0","Civilian","Ground"
	,"Hagglunds BV206","snowtruck03.jpg","Hagglunds BV206","snowtruck03.zip","1","0","0","Civilian","Ground"
	,"Snowmobile","snowtruck04.jpg","Snowmobile","snowtruck04.zip","1","0","0","Civilian","Ground"
	,"Snow Blower Truck","snowtruck05.jpg","Snow Blower Truck","snowtruck05.zip","1","0","0","Civilian","Ground"
	,"Snow Plow Truck","snowtruck06.jpg","Snow Plow Truck","snowtruck06.zip","1","0","0","Civilian","Ground"
	,"Construction Vehicle","fcciv01.jpg","Construction Vehicle","fcciv01.zip","1","0","0","Civilian","Ground"
	,"Construction Vehicle","fcciv04.jpg","Construction Vehicle","fcciv04.zip","1","0","0","Civilian","Ground"
	,"Steam Roller","VEHICM.jpg","Steam Roller","VEHICM.zip","1","0","0","Civilian","Ground"
	,"Hoover Repair Bot","VEHICO.jpg","Hoover Repair Bot","VEHICO.zip","1","0","0","Civilian","Ground"
	,"Construction Platform","VEHICT.jpg","Construction Platform","VEHICT.zip","1","0","0","Civilian","Ground"
	,"Pimpin' Dumper","VEHICX.jpg","Pimpin' Dumper","VEHICX.zip","1","0","0","Civilian","Ground"
	,"Construction Loader","VEHICZ.jpg","Construction Loader","VEHICZ.zip","1","0","0","Civilian","Ground"
	,"Bulldozer","civytrctr8.jpg","Bulldozer","civytrctr8.zip","1","0","0","Civilian","Ground"
	,"Log Loader Truck","civytrctr9.jpg","Log Loader Truck","civytrctr9.zip","1","0","0","Civilian","Ground"
	,"Log Loader Truck","civytrctr10.jpg","Log Loader Truck","civytrctr10.zip","1","0","0","Civilian","Ground"
	,"Construction Semi-trailer","tractrck.jpg","Construction Semi-trailer","tractrck.zip","1","0","0","Civilian","Ground"
	,"Logging Truck","trctr1.jpg","Logging Truck","trctr1.zip","1","0","0","Civilian","Ground"
	,"Front Loader","trctr2.jpg","Front Loader","trctr2.zip","1","0","0","Civilian","Ground"
	,"Front Loader","trctr3.jpg","Front Loader","trctr3.zip","1","0","0","Civilian","Ground"
	,"Digger","trctr5.jpg","Digger","trctr5.zip","1","0","0","Civilian","Ground"
	,"Bobcat","vhefarm9.jpg","Bobcat","vhefarm9.zip","1","0","0","Civilian","Ground"
	,"Caterpillar Truck","wrkcattrck.jpg","Caterpillar Truck","wrkcattrck.zip","1","0","0","Civilian","Ground"
	,"Cement Truck","wrkcemtrk.jpg","Cement Truck","wrkcemtrk.zip","1","0","0","Civilian","Ground"
	,"Drill Truck","wrkdrlltrck.jpg","Drill Truck","wrkdrlltrck.zip","1","0","0","Civilian","Ground"
	,"Bulldozer","workcar05.jpg","Bulldozer","workcar05.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain1.jpg","Train Engine","civtrain1.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain2.jpg","Train Engine","civtrain2.zip","1","0","0","Civilian","Ground"
	,"Train Passenger Car","civtrain3.jpg","Train Passenger Car","civtrain3.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain7.jpg","Train Engine","civtrain7.zip","1","0","0","Civilian","Ground"
	,"Train Passenger Car","civtrain8.jpg","Train Passenger Car","civtrain8.zip","1","0","0","Civilian","Ground"
	,"Train Passenger Car","civtrain14.jpg","Train Passenger Car","civtrain14.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain15.jpg","Train Engine","civtrain15.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain16.jpg","Train Engine","civtrain16.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain4.jpg","Train Engine","civtrain4.zip","1","0","0","Civilian","Ground"
	,"Train Car","civtrain5.jpg","Train Car","civcivtrain5.zip","1","0","0","Civilian","Ground"
	,"Train Passenger Car","civtrain6.jpg","Train Passenger Car","civtrain6.zip","1","0","0","Civilian","Ground"
	,"Train Engine","civtrain9.jpg","Train Engine","civtrain9.zip","1","0","0","Civilian","Ground"
	,"Train Car","civtrain10.jpg","Train Car","civtrain10.zip","1","0","0","Civilian","Ground"
	,"Train Car","civtrain11.jpg","Train Car","civtrain11.zip","1","0","0","Civilian","Ground"
	,"Train Car","civtrain12.jpg","Train Car","civtrain12.zip","1","0","0","Civilian","Ground"
	,"Train Car","civtrain13.jpg","Train Car","civtrain13.zip","1","0","0","Civilian","Ground"

	//Navy
	,"Speed Boat","fcciv12.jpg","Speed Boat","fcciv12.zip","1","0","0","Civilian","Naval"
	,"Speed Boat","fcciv13.jpg","Speed Boat","fcciv13.zip","1","0","0","Civilian","Naval"
	,"Speed Boat","fcciv15.jpg","Speed Boat","fcciv15.zip","1","0","0","Civilian","Naval"
	,"Speed Boat","fcciv16.jpg","Speed Boat","fcciv16.zip","1","0","0","Civilian","Naval"
	,"Speed Boat","fcciv17.jpg","Speed Boat","fcciv17.zip","1","0","0","Civilian","Naval"
	,"Speed Boat","fcciv18.jpg","Speed Boat","fcciv18.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat05.jpg","Sport Boat","boat05.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat06.jpg","Sport Boat","boat06.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat08.jpg","Sport Boat","boat08.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat09.jpg","Sport Boat","boat09.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat11.jpg","Sport Boat","boat11.zip","1","0","0","Civilian","Naval"
	,"Sport Boat","boat13.jpg","Sport Boat","boat13.zip","1","0","0","Civilian","Naval"
	,"Boat","civiboat01.jpg","Boat","civiboat01.zip","1","0","0","Civilian","Naval"
	,"Boat","civiboat02.jpg","Boat","civiboat02.zip","1","0","0","Civilian","Naval"
	,"Boat","civiboat03.jpg","Boat","civiboat03.zip","1","0","0","Civilian","Naval"
	,"Boat","civiboat04.jpg","Boat","civiboat04.zip","1","0","0","Civilian","Naval"
	,"Boat","CIVUSHIPA.jpg","Boat","CIVUSHIPA.zip","1","0","0","Civilian","Naval"
	,"Boat","CIVUSHIPB.jpg","Boat","CIVUSHIPB.zip","1","0","0","Civilian","Naval"
	,"Boat","CIVUSHIPF.jpg","Boat","CIVUSHIPF.zip","1","0","0","Civilian","Naval"
	,"Boat","CIVUSHIPG.jpg","Boat","CIVUSHIPG.zip","1","0","0","Civilian","Naval"
	,"Boat","CIVUSHIPI.jpg","Boat","CIVUSHIPI.zip","1","0","0","Civilian","Naval"
	,"Yacht","civyacht1.jpg","Civilian Yacht","civyacht1.zip","1","0","0","Civilian","Naval"
	,"Yacht","civyacht2.jpg","Civilian Yacht","civyacht2.zip","1","0","0","Civilian","Naval"
	,"Commercial Fishing Boat","fishboat01.jpg","Commercial Fishing Boat","fishboat01.zip","1","0","0","Civilian","Naval"
	,"Commercial Fishing Boat","fishboat02.jpg","Commercial Fishing Boat","fishboat02.zip","1","0","0","Civilian","Naval"
	,"Shipping Vessel","shipves.jpg","Shipping Vessel","shipves.zip","1","0","0","Civilian","Naval"
	,"Shipping Vessel","shipvessel.jpg","Shipping Vessel","shipvessel.zip","1","0","0","Civilian","Naval"
	,"Old Steam Ferry","steamferry.jpg","Old Steam Ferry","steamferry.zip","1","0","0","Civilian","Naval"
	,"Ferry","CIVUSHIPC.jpg","Ferry","CIVUSHIPC.zip","1","0","0","Civilian","Naval"
	,"Cruise Ship","cruisshi1.jpg","Cruise Ship","cruisshi1.zip","1","0","0","Civilian","Naval"
	,"Cruise Ship","cruisshi2.jpg","Cruise Ship","cruisshi2.zip","1","0","0","Civilian","Naval"
	,"Cruise Ship","CIVUSHIPD.jpg","Cruise Ship","CIVUSHIPD.zip","1","0","0","Civilian","Naval"
	,"Cruise Ship","CIVUSHIPE.jpg","Cruise Ship","CIVUSHIPE.zip","1","0","0","Civilian","Naval"
	,"Cruise Ship","CIVUSHIPH.jpg","Cruise Ship","CIVUSHIPH.zip","1","0","0","Civilian","Naval"
	,"Submarine","bluesub.jpg","Submarine","bluesub.zip","1","0","0","Civilian","Naval"
	,"Submarine","deepsub.jpg","Submarine","deepsub.zip","1","0","0","Civilian","Naval"
	,"Submarine","fastsub.jpg","Submarine","fastsub.zip","1","0","0","Civilian","Naval"
	,"Submarine","smallsub.jpg","Submarine","smallsub.zip","1","0","0","Civilian","Naval"
	,"Submarine","yellowsub.jpg","Submarine","yellowsub.zip","1","0","0","Civilian","Naval"

	//Other vxl
	//Aircraft
	,"Aircraft Fighter","migfight.jpg","Aircraft Fighter","migfight.zip","1","0","0","Other","Aerial"
	,"B-2 Bomber","b2.jpg","B-2 Bomber","b2.zip","1","0","0","Other","Aerial"
	,"Boeing 314 CLIPPER","boatplane.jpg","Boeing 314 CLIPPER","boatplane.zip","1","0","0","Other","Aerial"
	,"Bubble Cargo Plane","milbubble.jpg","Military Bubble Cargo Plane","milbubble.zip","1","0","0","Other","Aerial"
	,"Scout Helicopter","milchooper.jpg","Military Scout Helicopter","milchooper.zip","1","0","0","Other","Aerial"
	,"Carry-All","milchopper.jpg","Military Aircraft Carry-All","milchopper.zip","1","0","0","Other","Aerial"
	,"Renegade Orca","renorca.jpg","Renegade Orca conversion","renorca.zip","1","0","0","Other","Aerial"
	,"Giga Fortress","egiga.jpg","Giga Fortress","egiga.zip","1","0","0","Other","Aerial"
	,"Mecha/Jet Tengu","emchmig.jpg","Aircraft","emchmig.zip","1","0","0","Other","Aerial"
	,"Striker/Chopper VX","evxchp.jpg","Striker/Chopper VX","evxchp.zip","1","0","0","Other","Aerial"
	,"Rontovanna Bomber","type200.jpg","A unit from my old mod Internal Destruction (2005)","type200.zip","1","0","0","Other","Aerial"
	,"Zorgon Bomber","zorgair.jpg","A unit from my old mod Internal Destruction (2005)","zorgair.zip","1","0","0","Other","Aerial"
	,"Gunship","metroid.jpg","Samus Aran's Gunship","metroid.zip","1","0","0","Other","Aerial"
	,"BSG: Raider","bsgraider.jpg","Battlestar Galactica: Raider","bsgraider.zip","1","0","0","Other","Aerial"
	,"BSG: Heavy Raider","hevraid.jpg","Battlestar Galactica: Heavy Raider","hevraid.zip","1","0","0","Other","Aerial"
	,"BSG: Raptor","bsgrapt.jpg","Battlestar Galactica: Raptor","bsgrapt.zip","1","0","0","Other","Aerial"
	,"BSG: Viper MKII","vipermk2.jpg","Battlestar Galactica: Viper MKII","vipermk2.zip","1","0","0","Other","Aerial"
	,"BSG: Viper MKVII","vipermk7.jpg","Battlestar Galactica: Viper MKVII","vipermk7.zip","1","0","0","Other","Aerial"
	,"BSG: Blackbird","blackbird.jpg","Battlestar Galactica: Blackbird","blackbird.zip","1","0","0","Other","Aerial"
	,"B-wing starfighter","swbwing.jpg","Star Wars: B-wing starfighter","swbwing.zip","1","0","0","Other","Aerial"
	,"Y-wing starfighter","swywing.jpg","Star Wars: Y-wing starfighter","swywing.zip","1","0","0","Other","Aerial"
	,"TIE Fighter","swtiefight.jpg","Star Wars: TIE Fighter","swtiefight.zip","1","0","0","Other","Aerial"
	,"X-Wing","swxwing.jpg","Star Wars: X-Wing","swxwing.zip","1","0","0","Other","Aerial"
	,"UD-4L Cheyenne Dropship","aliensdrop.jpg","Aliens: UD-4L Cheyenne Dropship","aliensdrop.zip","1","0","0","Other","Aerial"
	,"The Bat","batwingrise.jpg","The Bat","batwingrise.zip","1","0","0","Other","Aerial"

	//Ground
	,"M577 Armored Personnel Carrier","aliensapc.jpg","Aliens: M577 Armored Personnel Carrier","aliensapc.zip","1","0","0","Other","Ground"
	,"Hand","justhand.jpg","Just a Hand","justhand.zip","1","0","0","Other","Ground"
	,"Swinger","austincar.jpg","Austin Powers car","austincar.zip","1","0","0","Other","Ground"
	,"Ecto-1","echo1.jpg","Ghostbusters: Ecto-1","echo1.zip","1","0","0","Other","Ground"
	,"General Lee","dukehcar.jpg","The Dukes of Hazzard car","dukehcar.zip","1","0","0","Other","Ground"
	,"Truckster","vacation.jpg","National Lampoon's Vacation","vacation.zip","1","0","0","Other","Ground"
	,"Gadgetmobile","gagetcar.jpg","Inspector Gadget: Gadgetmobile","gagetcar.zip","1","0","0","Other","Ground"
	,"M.A.D. Mobile","madcar.jpg","Inspector Gadget: M.A.D. Mobile is Dr. Claw's personal vehicle","madcar.zip","1","0","0","Other","Ground"
	,"Spinner","spinner.jpg","Blade Runner: police car","spinner.zip","1","0","0","Other","Ground"
	,"Flintstone Mobile","flint.jpg","Flintstone Mobile","flint.zip","1","0","0","Other","Ground"
	,"Landspeeder","swspeeder.jpg","Star Wars: Landspeeder","swspeeder.zip","1","0","0","Other","Ground"
	,"Batmobile (1966)","oldbatcar.jpg","Batman: Batmobile (1966)","oldbatcar.zip","1","0","0","Other","Ground"
	,"Batmobile","animabatman.jpg","Batman: Batmobile Animated series","animabatman.zip","1","0","0","Other","Ground"
	,"Batmobile","timbat.jpg","Batmobile","timbat.zip","1","0","0","Other","Ground"
	,"Tumbler","tumbler.jpg","Batman: Tumbler","tumbler.zip","1","0","0","Other","Ground"
	,"Batmobile (Batman Beyond)","batbeyond.jpg","Batmobile (Batman Beyond)","batbeyond.zip","1","0","0","Other","Ground"
	,"A-Team Van","ateam.jpg","A-Team Van","ateam.zip","1","0","0","Other","Ground"
	,"Cheech and Chong","chongvan.jpg","Cheech and Chong: Van","chongvan.zip","1","0","0","Other","Ground"
	,"Mystery Machine","mystryvan.jpg","Scooby-Doo: Mystery Machine","mystryvan.zip","1","0","0","Other","Ground"
	,"Mutt Cutts Van","dumbvan.jpg","Dumb and Dumber: The Mutt Cutts Van","dumbvan.zip","1","0","0","Other","Ground"
	,"Jeep","jpjeep.jpg","Jurassic Park: Jeep","jpjeep.zip","1","0","0","Other","Ground"
	,"Tour Vehicle","jpvan.jpg","Jurassic Park: Tour Vehicle","jpvan.zip","1","0","0","Other","Ground"
	,"Humvee","humr.jpg","Humvee","humr.zip","1","0","0","Other","Ground"
	,"Renegade Humvee","renhummer.jpg","Renegade Humvee conversion","renhummer.zip","1","0","0","Other","Ground"
	,"Humvee","milhumvee.jpg","Military Humvee","milhumvee.zip","1","0","0","Other","Ground"
	,"Half-Track","milhalf.jpg","Military Half-Track","milhalf.zip","1","0","0","Other","Ground"
	,"Military Truck","milhumtrck.jpg","Military Truck","milhumtrck.zip","1","0","0","Other","Ground"
	,"Military Truck","milbgtrck.jpg","Military Truck","milbgtrck.zip","1","0","0","Other","Ground"
	,"Military Truck","milbgtrcktop.jpg","Military Truck","milbgtrcktop.zip","1","0","0","Other","Ground"
	,"Military Truck","milsmltrck.jpg","Military Truck","milsmltrck.zip","1","0","0","Other","Ground"
	,"Military Truck","miltck.jpg","Military Truck","miltck.zip","1","0","0","Other","Ground"
	,"Military Truck","miltrckcab.jpg","Military Truck","miltrckcab.zip","1","0","0","Other","Ground"
	,"Military Truck","miltrcktop.jpg","Military Truck","miltrcktop.zip","1","0","0","Other","Ground"
	,"Bigfoot","bigfoot.jpg","Mad Max Fury Road: Rictus Erectus's 'Bigfoot'","bigfoot.zip","1","0","0","Other","Ground"
	,"Buggy no.9","buggy.jpg","Mad Max Fury Road: Perentti 'Buggy no.9'","buggy.zip","1","0","0","Other","Ground"
	,"Buick","buick.jpg","Mad Max Fury Road: Buick Special 4-door Sedan 1948 'Buick'","buick.zip","1","0","0","Other","Ground"
	,"Doof Wagon","doof.jpg","Mad Max Fury Road: MAN KAT I A1 (8x8) 'Doof Wagon'","doof.zip","1","0","0","Other","Ground"
	,"Dodge","douge.jpg","Mad Max Fury Road: Dodge","douge.zip","1","0","0","Other","Ground"
	,"The People Eater's Limousine","eater.jpg","Mad Max Fury Road: AM General M814 'The People Eater's Limousine'","eater.zip","1","0","0","Other","Ground"
	,"Elvis","elvis.jpg","Mad Max Fury Road: Ford 3 Window Coupe 1932 'Elvis'","elvis.zip","1","0","0","Other","Ground"
	,"The Peacemaker","farmer.jpg","Mad Max Fury Road: Howe and Howe Ripsaw EV1 'The Peacemaker'","farmer.zip","1","0","0","Other","Ground"
	,"FDK","fdk.jpg","Mad Max Fury Road: Volkswagen Type 1 'FDK'","fdk.zip","1","0","0","Other","Ground"
	,"Firecar #4","firecar.jpg","Mad Max Fury Road: Firecar #4","firecar.zip","1","0","0","Other","Ground"
	,"Cranky Frank","frank.jpg","Mad Max Fury Road: Holden FJ Utility 'Cranky Frank'","frank.zip","1","0","0","Other","Ground"
	,"The Gigahorse","giga.jpg","Mad Max Fury Road: The Gigahorse","giga.zip","1","0","0","Other","Ground"
	,"Mack","mack.jpg","Mad Max Fury Road: Mack","mack.zip","1","0","0","Other","Ground"
	,"The Nux Car","nux.jpg","Mad Max Fury Road: Chevrolet 5 Window Coupe 1934 'The Nux Car'","nux.zip","1","0","0","Other","Ground"
	,"Ploughboy","ploughboy.jpg","Mad Max Fury Road: Holden EK Special Station Wagon 1961 'Ploughboy'","ploughboy.zip","1","0","0","Other","Ground"
	,"Prince Valiant","prince.jpg","Mad Max Fury Road: Prince Valiant","prince.zip","1","0","0","Other","Ground"
	,"The War Rig","warrig.jpg","Mad Max Fury Road: Tatra T815 'The War Rig'","warrig.zip","1","0","0","Other","Ground"
	,"Zorgon Mech","mech.jpg","A unit from my old mod Internal Destruction (2005)","mech.zip","1","0","0","Other","Ground"
	,"Rontovanna Harvester","ronharv.jpg","A unit from my old mod Internal Destruction (2005)","ronharv.zip","1","0","0","Other","Ground"
	,"Rontovanna type-25","type25.jpg","A unit from my old mod Internal Destruction (2005)","type25.zip","1","0","0","Other","Ground"
	,"Rontovanna type-50","type50.jpg","A unit from my old mod Internal Destruction (2005)","type50.zip","1","0","0","Other","Ground"
	,"Rontovanna type-75","type75.jpg","A unit from my old mod Internal Destruction (2005)","type75.zip","1","0","0","Other","Ground"
	,"Wave Force Artillery","elsrcn.jpg","Wave Force Artillery","elsrcn.zip","1","0","0","Other","Ground"
	,"Mobile Construction Vehicle","emcv.jpg","Mobile Construction Vehicle","emcv.zip","1","0","0","Other","Ground"
	,"Tsunami Tank","etstnk.jpg","Tsunami Tank","etstnk.zip","1","0","0","Other","Ground"
	,"C&C3's GDI's epic unit: Marv","marv.jpg","The vxl I submitted to a PPM VoxelComp,but I disqualified myself do to poor organization<br>C&C3's GDI's epic unit: Marv","MARV_PPM_VXL_COMP.zip","1","1","0","Other","Ground"
	,"Tesla Turtle","tt.JPG","The vxl I submitted to the May/June 2004 CNCG Voxel Competition, And got 1st place<br>Tesla Turtle","tt.zip","1","0","0","Other","Ground"
	,"King Kong","kingkong.jpg","King Kong","kingkong.zip","1","0","0","Other","Ground"

	//Navy
	,"Naginata Cruiser","enagin.jpg","Naginata Cruiser","enagin.zip","1","0","0","Other","Naval"
	,"Sea-Wing","esewng.jpg","Sea-Wing","esewng.zip","1","0","0","Other","Naval"
	,"Yari mini-sub","etsub.jpg","Yari mini-sub","etsub.zip","1","0","0","Other","Naval"
	,"Shogun Battleship","eshgn.jpg","Shogun Battleship","eshgn.zip","1","0","0","Other","Naval"
	,"Landing Craft Air Cushion","bglncfrt.jpg","Landing Craft Air Cushion (LCAC)","bglncfrt.zip","1","0","0","Other","Naval"
	,"Landing Craft","lndcrft.jpg","Landing Craft","lndcrft.zip","1","0","0","Other","Naval"
	,"A FRICKIN SHARK WITH A LASER ON ITS HEAD!!!","whale.JPG","A FRICKIN SHARK WITH A LASER ON ITS HEAD!!!","shrkwlazr.zip","1","0","0","Other","Naval"
);

?>