<?php

$twoMapsYRPage2=array(//2 player maps
	"Woody Island (2)","woody.jpg","An island map made from a google maps satellite image","woody.jpg","woody.zip","newurban","150x150"
	,"Spartly Island (2)","spratlyis.jpg","An island map made from a google maps satellite image","spratlyis.jpg","spratlyis.zip","newurban","137x135"
	,"Village Circuit (2)","vicircuit.jpg","A 2 player symmetrical map","vicircuit.jpg","vicircuit.zip","temperate","107x110"
	,"Hamlet Mirror (2)","hamlet.jpg","A 2 player symmetrical map","hamlet.jpg","hamlet.zip","temperate","110x115"
	,"Jungle Basin (2)","junglebasin.jpg","A SC2 re-make map","junglebasin.jpg","junglebasin.zip","temperate","112x143"
	,"Road Rage (2)","roadrage.jpg","An odd map with a bunch of neutral spawning vehicals","roadrage.jpg","roadrage.zip","urban","75x78"
	,"Virgin Moscow (2)","virginmoscow.jpg","An odd map with a bunch of neutral spawning infantry","virginmoscow.jpg","virginmoscow.zip","snow","77x77"
	,"BloodShed Reef (2)","bloodreef.jpg","An island map made from a google maps satellite image","bloodreef.jpg","bloodreef.zip","temperate","190x110"
	,"Car Park Shift (2)","carhift.jpg","A re-sizeing map, about 15 min tell map gets wider and opens ground path<br>Red lines show starting size","carhift.jpg","carhift.zip","urban","128x127"
	,"Halo Destruction (2)","halo.jpg","A small 2 player symmetrical map","halo.jpg","halo.zip","temperate","95x95"
	,"Public Combat (2)","pubcom.jpg","A small 2 player urban map, theme based off Bay of Pigs","pubcom.jpg","pubcom.zip","urban","75x78"
	,"Situation Critical (2)","situation.jpg","A Red Alert map made for Yuris Revenge","situation.jpg","situation.zip","snow","120x170"
	);

$threeMapsYRPage2=array(//3 player maps
	"Little Mermaid (2-3)","litmer.jpg","A 3 player island map in the shape of a Mermaid","litmer.jpg","litmer.zip","temperate","200x125"
	,"Easter Island (2-3)","easterisl.jpg","A 3 player island map made from a google maps satellite image","easterisl.jpg","easterisl.zip","temperate","170x130"
	,"Cubed Combat (2-3)","cubcomb.jpg","A 3 player symmetrical map","cubcomb.jpg","cubcomb.zip","desert","138x147"
	,"Squid Reef (2-3)","squid.jpg","A map made to look like a Squid","squid.jpg","squid.zip","temperate","148x147"
	,"Dolphin Party (2-3)","dolphin.jpg","A map made to look like a Dolphin","dolphin.jpg","dolphin.zip","temperate","188x107"
	,"Marshall Island (2-3)","marland.jpg","An island map re-sizeing map, with a nuke strike at the center","marland.jpg","marland.zip","temperate","115x150"
	,"Dahlac Marine (2-3)","dahlac.jpg","An island map made from a google maps satellite image","dahlac.jpg","dahlac.zip","desert","175x120"
	,"Coburg Island(2-3)","coburg.jpg","An island map made from a google maps satellite image","coburg.jpg","coburg.zip","snow","152x143"
	,"Aegean Sea (2-3)","aegean.jpg","An island map made from a google maps satellite image","aegean.jpg","aegean.zip","temperate","180x120"
	,"Isla Nublar (2-3)","nublar.jpg","NA-NUH-NA-NA-NAH! Welcome to Jurassic Park!","nublar.jpg","nublar.zip","temperate","144x171"
	,"Blizzard Triplication (2-3)","triplication.jpg","A 3 player snow symmetrical island map","triplication.jpg","triplication.zip","snow","120x145"
	);

$fourMapsYRPage2=array(//4 player maps
	"Akhiok Island (2-4)","akhiok.jpg","A 4 player island map made from a google maps satellite image","akhiok.jpg","akhiok.zip","desert","145x150"
	,"Chankliut Island (2-4)","chankliut.jpg","A 4 player island map made from a google maps satellite image","chankliut.jpg","chankliut.zip","snow","150x152"
	,"Yin-Yang (2-4)","yinyang.jpg","A 4 player symmetrical island Yin-Yang map","yinyang.jpg","yinyang.zip","snow","160x170"
	,"Arid Mitosis (2-4)","aridmit.jpg","A 4 player symmetrical map","aridmit.jpg","aridmit.zip","desert","148x157"
	,"Witch Haven (2-4)","witchmap.jpg","Happy Halloween!!!<br>A silly halloween themed 4 player map","witchmap.jpg","witchmap.zip","temperate","139x151"
	,"Distric of Colombia (2-4)","dcolombia.jpg","An map of Distric of Colombia","dcolombia.jpg","dcolombia.zip","newurban","115x140"
	,"Skull Islands (2-4)","skullis.jpg","A 4 player symmetrical map","skullis.jpg","skullis.zip","temperate","140x150"
	,"Kickin' Company (2-4)","company.jpg","An island map made from a google maps satellite image","company.jpg","company.zip","temperate","181x114"
	,"Desolate Metropolis (2-4)","desometro.jpg","A 4 player symmetrical map","desometro.jpg","desometro.zip","desert","260x135"
	,"To The ARC (2-4)","toarc.jpg","An odd map with a bunch of neutral spawning animals","toarc.jpg","toarc.zip","temperate","104x104"
	,"Auto Downfall (2-4)","autodown.jpg","An odd map with a bunch of neutral spawning vehicals","autodown.jpg","autodown.zip","urban","103x121"
	,"Abeloya(2-4)","abeloya.jpg","An island map made from a google maps satellite image","abeloya.jpg","abeloya.zip","snow","165x130"
	,"Rocky Surf (2-4)","rockysurf.jpg","An island map made from a google maps satellite image","rockysurf.jpg","rockysurf.zip","temperate","140x180"
	,"Dusty Canyon (2-4)","duscan.jpg","A 4 player symmetrical map","duscan.jpg","duscan.zip","temperate","100x100"
	,"The Pinch (2-4)","pinch.jpg","A 4 player symmetrical map with a central choke point","pinch.jpg","pinch.zip","desert","125x100"
	,"Aqua Speculum (2-4)","aqua.jpg","A 4 player symmetrical island map thats great for navel battles","aqua.jpg","aqua.zip","temperate","120x145"
	);

$fiveMapsYRPage2=array(//5 player maps
	"Shredder (2-5)","shredder.jpg","A symmetrical island map","shredder.jpg","shredder.zip","snow","168x167"
	,"Mount Yamantau (2-5)","yamantau.jpg","A asymmetrical map made from Polygon Map Generation, from Red Blob Games","yamantau.jpg","yamantau.zip","snow","160*160"
	,"Evil Eyes (2-5)","eyes.jpg","Happy Halloween!!!<br>A silly halloween themed 5 player map","eyes.jpg","eyes.zip","snow","235*120"
	,"Baphomet (2-5)","baphomet.jpg","Happy Halloween!!!<br>A silly halloween themed 5 player map","baphomet.jpg","baphomet.zip","temperate","160*160"
	,"Arid Superiority (2-5)","arisup.jpg","A asymmetrical map made from Polygon Map Generation, from Red Blob Games","arisup.jpg","arisup.zip","desert","160x160"
	,"Lost Valley (2-5)","losvall.jpg","A symmetrical map based on a map from C&C 4","losvall.jpg","losvall.zip","temperate","200x200"
	,"Capital Coup (2-5)","hauptsta.jpg","A symmetrical map based on a map from C&C 4","hauptsta.jpg","hauptsta.zip","urban","200x200"
	,"Communist Combat (2-5)","soviet.jpg","An map in the shape of the Soviet logo","soviet.jpg","soviet.zip","desert","150x155"
	,"Kongsoya (2-5)","kongsoya.jpg","An island map made from a google maps satellite image","kongsoya.jpg","kongsoya.zip","snow","175x140"
	,"Santorini Island (2-5)","santorini.jpg","An island map made from a google maps satellite image","santorini.jpg","santorini.zip","temperate","160x175"
	);

$sixMapsYRPage2=array(//6 player maps
	"Puzzling Peninsula (2-6)","puzpen.jpg","A asymmetrical map of puzzle pieces","puzpen.jpg","puzpen.zip","newurban","200x200"
	,"Withered Fracture (2-6)","withfrac.jpg","A symmetrical map based on a map from C&C 4","withfrac.jpg","withfrac.zip","desert","200x200"
	,"Arid Arachnid (2-6)","spidermap.jpg","Happy Halloween!!!<br>A silly halloween themed 6 player map","spidermap.jpg","spidermap.zip","desert","144x151"
	,"Devils Refuge (2-6)","devilmap.jpg","Happy Halloween!!!<br>A silly halloween themed 6 player map","devilmap.jpg","devilmap.zip","snow","147x148"
	,"Reaper Enclave (2-6)","grimmap.jpg","Happy Halloween!!!<br>A silly halloween themed 6 player map","grimmap.jpg","grimmap.zip","temperate","137x168"
	,"In The Seam (2-6)","theseam.jpg","A symmetrical 6 player map","theseam.jpg","theseam.zip","temperate","249x145"
	,"Sextuplet Bluff (2-6)","sextuplet.jpg","A symmetrical 6 player map","sextuplet.jpg","sextuplet.zip","desert","252x124"
	,"Mirage Shock Sector (2-6)","mirageshock.jpg","An island map made from a google maps satellite image","mirageshock.jpg","mirageshock.zip","desert","159x146"
	,"Agattu Island (2-6)","agattu.jpg","An island map made from a google maps satellite image","agattu.jpg","agattu.zip","temperate","155x180"
	,"Straight Shot (2-6)","straight.jpg","A symmetrical 6 player map","straight.jpg","straight.zip","temperate","128x127"
	,"Civic Violence (2-6)","civvio.jpg","A large 6 player urban map","civvio.jpg","civvio.zip","urban","125x150"
	);

$sevenMapsYRPage2=array(//7 player maps
	"Inner-City Toil (2-7)","citytoil.jpg","A asymmetrical map made from Polygon Map Generation, from Red Blob Games","citytoil.jpg","citytoil.zip","urban","178x177"
	,"Bunny Bowl (2-7)","bunybowl.jpg","A asymmetrical map made with a body of water in the shape of a bunny","bunybowl.jpg","bunybowl.zip","urban","142x193"
	,"Metropolis Height (2-7)","metroheight.jpg","A asymmetrical map made from Polygon Map Generation, from Red Blob Games","metroheight.jpg","metroheight.zip","newurban","160x160"
	,"Jason (2-7)","jason.jpg","Happy Halloween!!!<br>A silly halloween themed 7 player map","jason.jpg","jason.zip","newurban","150*150"
	,"Dusty Bones (2-7)","dustybones.jpg","Happy Halloween!!!<br>A silly halloween themed 7 player map","dustybones.jpg","dustybones.zip","desert","170*230"
	,"Midnight Splat (2-7)","midnsp.jpg","A asymmetrical map made from Polygon Map Generation, from Red Blob Games","midnsp.jpg","midnsp.zip","temperate","160x160"
	,"Icy Cellar (2-7)","icycell.jpg","A symmetrical map based on a map from C&C 4","icycell.jpg","icycell.zip","snow","200x200"
	,"Circal Jerk (2-7)","circaljerk.jpg","A symmetrical 7 player map, the center player gets extra stuff","circaljerk.jpg","circaljerk.zip","urban","129x125"
	,"Nora Island (2-7)","nora.jpg","An island map made from a google maps satellite image","nora.jpg","nora.zip","desert","160x145"
	,"Tokashiki (2-7)","tokashiki.jpg","An island map made from a google maps satellite image","tokashiki.jpg","tokashiki.zip","temperate","160x135"
	);

$eightMapsYRPage2=array(//8 player maps
	"Terrortial Imperative HD (2-8)","terrimp.jpg","A large remake of Terrortial Imperative from Red Alert 2","terrimp.jpg","terrimp.zip","temperate","220x180"
	,"Heck Freezes Over HD (2-8)","hckfreovr.jpg","A large remake of Heck Freezes Over from Red Alert 2","hckfreovr.jpg","hckfreovr.zip","snow","190x210"
	,"Trailer Park HD (2-8)","tralprk.jpg","A large remake of Trailer Park from Red Alert 2","tralprk.jpg","tralprk.zip","temperate","240x160"
	,"A Path Beyond II HD (2-8)","apthbynd.jpg","A large remake of A Path Beyond II from Red Alert 2","apthbynd.jpg","apthbynd.zip","temperate","188x212"
	,"Pacific Rim (2-8)","pacfrim.jpg","A large 8 player map","pacfrim.jpg","pacfrim.zip","temperate","200x200"
	,"Icy Pinch (2-8)","icypnch.jpg","A large 8 player map","icypnch.jpg","icypnch.zip","snow","200x200"
	,"Divide and Conquer (2-8)","divconq.jpg","A large 8 player map","divconq.jpg","divconq.zip","snow","200x200"
	,"Eagle Island (2-8)","eaglislnd.jpg","A large 8 player map","eaglislnd.jpg","eaglislnd.zip","temperate","200x200"
	,"Coastal Influence (2-8)","costinfl.jpg","A large 8 player map","costinfl.jpg","costinfl.zip","temperate","200x200"
	,"Eriond (2-8)","eriond.jpg","A large 8 player map","eriond.jpg","eriond.zip","snow","200x200"
	,"Forsaken Waste (2-8)","forsawast.jpg","A large 8 player map","forsawast.jpg","forsawast.zip","desert","200x200"
	,"Tundra Trouble (2-8)","tundtro.jpg","A large 8 player map","tundtro.jpg","tundtro.zip","snow","200x200"
	,"Trumpnation (2-8)","trumpnation.jpg","Welcome to Trumpnation!","trumpnation.jpg","trumpnation.zip","temperate","145x145"
	,"Central Quad (2-8)","centquad.jpg","A symmetrical 8 player map","centquad.jpg","centquad.zip","newurban","133x132"
	,"The Great Divide (2-8)","divide.jpg","A large 8 player map","divide.jpg","divide.zip","temperate","200x200"
	,"Earth (2-8)","earth.jpg","A large 8 player map","earth.jpg","earth.zip","temperate","272x158"
	,"Paramenides (2-8)","paramenides.jpg","A large 8 player map","paramenides.jpg","paramenides.zip","snow","272x158"
	,"Trinity (2-8)","trinity.jpg","A large 8 player map of Earth covered in snow","trinity.jpg","trinity.zip","temperate","272x158"
	,"Plush Bluff (2-8)","plush.jpg","A large 8 player map","plush.jpg","plush.zip","desert","131x135"
	,"Arctic Twist (2-8)","arctictwist.jpg","A large 8 player map","arctictwist.jpg","arctictwist.zip","snow","133x136"
	,"Chilled To The Bone (2-8)","chilled.jpg","A large 8 player map","chilled.jpg","chilled.zip","snow","148x147"
	,"Ice Age (2-8)","iceage.jpg","A large 8 player map of Earth covered in snow","iceage.jpg","iceage.zip","snow","199x199"
	,"Valley of Death (2-8)","valleydeath.jpg","A large 8 player map","valleydeath.jpg","valleydeath.zip","temperate","199x199"
	,"Desert Credit (2-8)","credit.jpg","A large 8 player desert map","credit.jpg","credit.zip","desert","199x199"
	,"Port Royal (2-8)","portroy.jpg","A large 8 player new urban map. For fun, 4 Smaller maps made from this map.<br>"
		. "Unfair Grounds (2) Size:150x100 Screenshot:<a href='/maps/full/fairgro.jpg' target='_blank' style='color:red;'>Click Here</a> Download:<a href='/maps/maps/fairgro.zip' style='color:red;' download>Click Here</a><br>"
		. "Northern Metropolis (2) Size:85x185 Screenshot:<a href='/maps/full/normetro.jpg' target='_blank' style='color:red;'>Click Here</a> Download:<a href='/maps/maps/normetro.zip' style='color:red;' download>Click Here</a><br>"
		. "Branched Boondocks (2) Size:125x85 Screenshot:<a href='/maps/full/branboon.jpg' target='_blank' style='color:red;'>Click Here</a> Download:<a href='/maps/maps/branboon.zip' style='color:red;' download>Click Here</a><br>"
		. "Downtown Encounter (2-3) Size:100x150 Screenshot:<a href='/maps/full/downtown.jpg' target='_blank' style='color:red;'>Click Here</a> Download:<a href='/maps/maps/downtown.zip' style='color:red;' download>Click Here</a>","portroy.jpg","portroy.zip","newurban","200x200"
	,"Dusty Avalanche (2-8)","dustava.jpg","A large 8 player desert map","dustava.jpg","dustava.zip","desert","178x178"
	,"Territory Encroachment (2-8)","encroachment.jpg","A large 8 player temperate map","encroachment.jpg","encroachment.zip","temperate","200x200"
	,"Bow-Tie Canyon (2-8)","bowtie.jpg","A symmetrical 8 player map","bowtie.jpg","bowtie.zip","temperate","169x152"
	,"In The Pipe (2-8)","pipe.jpg","A symmetrical 8 player map","pipe.jpg","pipe.zip","desert","70x185"
	,"Frosted Reft (2-8)","frostedreft.jpg","A symmetrical 8 player map","frostedreft.jpg","frostedreft.zip","snow","131x136"
	);

?>